### ISSUE TITLE
Missing Biome: Mangrove Swamp

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/antique-atlas#1]
Tiles, texture sets, and textures need to be added for mangrove swamps (1.19+)

This is currently covered by the regular swamp texture thanks to the swamp tag.

**Comment by IdrisQe** [comment]
Hey, not sure why it's not working, but the swamp tag compat doesn't seem to be functional in my 1.20.1 Forge server?
Mangrove swamps are appearing like... This.
![image](https://github.com/sisby-folk/antique-atlas/assets/40530630/dcc205f5-9b11-446c-9617-9e29d561e6e8)

Any idea what the cause could be? Using 9.0.1 for Forge.

**Comment by sleepingdragoninn** [comment]
at a guess? that probably means mangrove swamps aren't actually in the IS_SWAMP tag. We'll see if we can't patch that out.

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/59ffaf29-1831-4544-bdb6-fd7895ef8494)
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/f8d03cbc-b225-4abf-ad8f-6d5229963e80)

**Comment by IdrisQe** [comment]
It'd be nice to see that fixed.

Something else I might suggest is a better fallback texture, even if it's just blank-looking paper.

Edit: It... seems to have fixed itself somehow?
I have no idea what changed but today, randomly, it's started working again.
I wonder if something was breaking the biome tags in my world?
![image](https://github.com/sisby-folk/antique-atlas/assets/40530630/0635eaed-6f2d-40c2-8650-092cfadb3c8b)

**Comment by sleepingdragoninn** [comment]
Yeah can't reproduce that in a test environment - I think it was just a tag oddity - glad it worked out!

**Comment by IdrisQe** [comment]
It didn't actually work out, it's back to being broken again. Not just Mangrove, but Cherry biomes too. Getting LMFT to see if something's butchering our biome tags because I have no idea what's causing this.
