### ISSUE TITLE
[internal exception java.net.socketexception connection reset] when joining a server.

### ISSUE THREAD

**Issue by Amliko** [sleepingdragoninn/antique-atlas#101]
Antique Atlas Version: 2.7.1+1.20
Surveyor Version: 0.5.0
Minecraft version: 1.21

Here is the in game error
![Here is the in game error](https://github.com/sisby-folk/antique-atlas/assets/152310810/e42318e9-0a61-4f81-87d2-c135b57e7885)
Here is the server side error
![Here is the server side error](https://github.com/sisby-folk/antique-atlas/assets/152310810/9bda7328-2f9d-4997-aadd-177a136f4bcf)

I have not added any extra mods after those two, though they are in a modpack which was unchanged since the begining, Antique atlas worked for several days before with no issues, and only yesterday stopped. Even then, it only caused me to disconnect in the overworld. I could have been anywhere in the nether fine, but as soon as i went through the portal my client would crash, and i would be unable to rejoin the server again until i was teleported into the nether. 

When looking into the crash logs in my client is showed this
![When looking into the crash logs in my client is showed this](https://github.com/sisby-folk/antique-atlas/assets/152310810/65753c51-a1d5-4d06-8c0f-1b4e996a9220)

Server side, there were no crash logs or information other then the fact i Disconnected.

The only fix I currently discovered and posses is to go into /data/surveyor and delete the whole /surveyor folder which WILL remove all your discovered areas and map progression.

**Comment by sleepingdragoninn** [comment]
can you post the full `logs/latest.log` of the client to https://mclo.gs/ ? that should illuminate the issue more clearly.

if the server is yours, you can stop it, restart it, then attempt to connect - then you can posts its latest.log as well, which might help.

**Comment by sleepingdragoninn** [comment]
stale-closing - let me know if you can get a log!
