### ISSUE TITLE
TerraFirmaCraft biomes issue

### ISSUE THREAD

**Issue by onlive1337** [sleepingdragoninn/antique-atlas#102]
wassup, i tried to add custom biomes from terrafirmacraft into Atlas but configuration guide wrote in github is really hard to understand, can i contact to developer on discord or something else to more completely guide, i really wanna see this biomes and i wanna contribute in this project

**Comment by sleepingdragoninn** [comment]
Hey there! We've got a chunk of free time tonight so we'll spin up a proper resource pack wiki page for the 2.0 format - then if you've still got questions feel free to ask!

For TFC specifically you may end up needing #103 which I've just spun up as I think it doesn't use unique biomes per it's terrain

**Comment by onlive1337** [comment]
unfortunately TFC uses partly unique biomes, screenshot of example here:
![tfc_issue](https://github.com/sisby-folk/antique-atlas/assets/102153021/36c0bcda-bc8f-4878-be8b-bd6666d53323)

**Comment by onlive1337** [comment]
it would be pretty cool if i connect unique biomes into minecraft default biomes or just disable unknown symbol

**Comment by sleepingdragoninn** [comment]
The issue with TFC is i believe it uses the same biome ID for multiple environments - so a plain and a forest might have the same biome ID - hence needing to detect leaves.

**Comment by onlive1337** [comment]
can u mention which json file i need to edit?

**Comment by sleepingdragoninn** [comment]
[wiki page](https://github.com/sisby-folk/antique-atlas/wiki/Resource-Packs) is up now.
