### ISSUE TITLE
Forge 1.20.1 Support

### ISSUE THREAD

**Issue by DamnedDisciple** [sleepingdragoninn/antique-atlas#104]
I’m making this post to inquire about the Forge 1.20.1 update. I wanted to use the Antique Atlas in my mod-pack for 1.20.1, but every time I tried to access it in the mods section it wouldn’t register. I definitely had it in the mods folder, but every time I open the in-game mods list, it didn’t show up as if I wasn’t in the folder.
 It was forge 1.20.1, I had connector and FFAPI, both those and the mod were in the mods folder, and I insured it was the right version of the mod. 
I asked if anyone else had a similar issue as I did, and sure enough someone did. They suggested I report it as a bug, so I am.
In all honesty, I have no idea whether it really is a bug or if I’m somehow missing something, but either way I decided to bring it to attention.

**Comment by sleepingdragoninn** [comment]
send your logs/latest.log via https://mclo.gs/ and we should be able to tell you where it's going wrong

**Comment by DamnedDisciple** [comment]
I was able to figure it out!

C:\Users\********\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.30\javafmllanguage-1.20.1-47.2.30.jar is missing mods.toml file
--
13 | [11May2024 23:26:00.341] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\********\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.30\lowcodelanguage-1.20.1-47.2.30.jar is missing mods.toml file
14 | [11May2024 23:26:00.345] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\********\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.30\mclanguage-1.20.1-47.2.30.jar is missing mods.toml file

I was originally attempting to download the mod via the Aternos listed requirements, but they were obviously wrong. When i tried downloading them directly from modrinth, the FFAPI .jar name was a fabric api name, and wrongfully assumed it _was_ the fabric api. I had to add the additional api as well, which i figured out from mclo.

Thank you for your help,
