### ISSUE TITLE
Map exploration progress is missing when auth fails

### ISSUE THREAD

**Issue by K0rS1z** [sleepingdragoninn/antique-atlas#105]
(English is not my language, I'm sorry) Hi, I'm one of the developers of a modpack. We would like to add this mod to our modpack, but we ran into this issue: after loading the map and attaching labels on it, when re-entering the game, the map is cleared, but the labels remain. If you go back into the world after leaving it, nothing will reset. It also doesn't matter which dimension to go out in.

I tried to create a new instance and leave only Atlas, Sinytra Connector, Forgified Fabric API there, the same thing.

Atlas - **2.7.2**
Sinytra Connector - **1.0.0-beta.43+1.20.1**
Forgified Fabric API - **0.92.1+1.11.8+1.20.1**
NeoForge - **1.20.1-47.1.105**

Before the map is reset:
https://mclo.gs/KSb8zv9 - latest.log
https://mclo.gs/EbnQlhg - debug.log

![2024-05-19_12 42 52](https://github.com/sisby-folk/antique-atlas/assets/142387212/f5640708-50c7-4927-ad63-8240599bdb40)
![2024-05-19_12 43 19](https://github.com/sisby-folk/antique-atlas/assets/142387212/a9e0ff62-f5b6-44eb-8354-9d1583bbe605)
![2024-05-19_12 43 43](https://github.com/sisby-folk/antique-atlas/assets/142387212/e6abd131-d1ed-42de-8019-0a4c951b3331)

After reset of the map:
https://mclo.gs/2eFA0bQ - latest.log
https://mclo.gs/nvlzV3D - debug.log

![2024-05-19_12 46 38](https://github.com/sisby-folk/antique-atlas/assets/142387212/55115ddc-86a0-4055-9118-edbea94d82c4)
![2024-05-19_12 45 41](https://github.com/sisby-folk/antique-atlas/assets/142387212/cfae94c0-2008-4ab8-8bbb-a77935ff8466)
![2024-05-19_12 45 19](https://github.com/sisby-folk/antique-atlas/assets/142387212/9d7a658d-f04f-47bd-b88e-50470c3d89fb)

**Comment by K0rS1z** [comment]
At the same time, everything is fine in the data folder, all files are in place. I also looked through NBTExplorer.
![2024-05-19_125909](https://github.com/sisby-folk/antique-atlas/assets/142387212/bee31cd9-ffe3-4742-805e-e863722d94cb)

**Comment by DmitryKuchin** [comment]
Same problem

**Comment by sleepingdragoninn** [comment]
This may be a piracy issue? - Antique Atlas stores your map exploration progress using your UUID - if that changes unexpectedly, your map data could be lost.

The markers sticking around lead me to believe there's something more going on here though - as they use UUIDs too, I'll look into it.

In the meantime, just set `shareAllTerrain` and `shareAllStructures` to true on your client - that will skip per-player client exploration visiblity and should resolve the issue.

**Comment by sleepingdragoninn** [comment]
As a side note, connector only officially supports Forge 47.1.3.

**Comment by K0rS1z** [comment]
> This may be a piracy issue? - Antique Atlas stores your map exploration progress using your UUID - if that changes unexpectedly, your map data could be lost.
> 
> The markers sticking around lead me to believe there's something more going on here though - as they use UUIDs too, I'll look into it.
> 
> In the meantime, just set `shareAllTerrain` and `shareAllStructures` to true on your client - that will skip per-player client exploration visiblity and should resolve the issue.

No, there is no piracy here. This is the same licensed account, I use an ATLauncher. This is a new world I created. I specially put a lot of labels so that you can clearly see how the map is being reset. 😅

**Comment by sleepingdragoninn** [comment]
mojang account or no, authlib is failing to generate a profile, and atlas relies heavily on it - try the workaround in the meantime? idk if a mod or what is breaking your auth, but you can see it in the log. (offline mode server maybe?)

**Comment by K0rS1z** [comment]
> As a side note, connector only officially supports Forge 47.1.3.

But this is interesting... I recently tried this mod on different versions and its various forks - the bug is everywhere. Only here at least the labels remain, for others the map is completely reset.

**Comment by K0rS1z** [comment]
> mojang account or no, authlib is failing to generate a profile, and atlas relies heavily on it - try the workaround in the meantime? idk if a mod or what is breaking your auth, but you can see it in the log. (offline mode server maybe?)

Strange... I'll try other launchers. I'm checking in the single world, not on the server. 🤔

**Comment by K0rS1z** [comment]
> mojang account or no, authlib is failing to generate a profile, and atlas relies heavily on it - try the workaround in the meantime? idk if a mod or what is breaking your auth, but you can see it in the log. (offline mode server maybe?)

What's the workaround?

**Comment by sleepingdragoninn** [comment]
set the shareAllTerrain and shareAllStructures true in the config toml

**Comment by K0rS1z** [comment]
> set the shareAllTerrain and shareAllStructures true in the config toml

Ok, let's try it

**Comment by K0rS1z** [comment]
> set the shareAllTerrain and shareAllStructures true in the config toml

It really worked! By the way, yes, I just noticed right now that I rarely change my skin to one of the standard ones without a cape. Hmm

**Comment by K0rS1z** [comment]
But if this happens (suddenly) on the server, it turns out that everyone will share the map with each other (without labels).

**Comment by sleepingdragoninn** [comment]
Yep - that would be auth failing. when auth fails, you lose your skin, and would also lose any map exploration.

**Comment by K0rS1z** [comment]
> Yep - that would be auth failing. when auth fails, you lose your skin, and would also lose any map exploration.

I studied my logs and it turns out that authentication can sometimes pass, and sometimes not. Maybe it's the launcher.

**Comment by BitCatalyst7** [comment]
> set the shareAllTerrain and shareAllStructures true in the config toml

Hey, Don't mean to come onto a dead thread, but I'm having the same issue and these values are not in the config for me. Unless I'm looking in the wrong place.

**Comment by MUKSC** [comment]
@BitCatalyst7 It's in the `surveyor.toml` file

**Comment by sleepingdragoninn** [comment]
We should be solving this in singleplayer via https://github.com/sisby-folk/surveyor/issues/22

**Comment by sleepingdragoninn** [comment]
should be fixed in 2.9.6

**Comment by Sk1nny18** [comment]
hi im looking into the surveyor.toml file and there is no values for

> set the shareAllTerrain and shareAllStructures true in the config toml
