### ISSUE TITLE
Tooltips Exit Screen Bounds

### ISSUE THREAD

**Issue by AmazeingGames** [sleepingdragoninn/antique-atlas#107]
The tooltips for Antique Atlas go off the bounds of the screen, even when utilizing mods like [Adaptive Tooltips ](https://www.curseforge.com/minecraft/mc-mods/adaptive-tooltips) or [Tooltip Fix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix). Tested on Minecraft 1.20.1; Forge 47.2.6; Utilized Synetra Connector and Synetra Extra.

![Screenshot (678)](https://github.com/sisby-folk/antique-atlas/assets/106894328/75e77235-768d-414e-a1a1-d1d15b16af55)
![Screenshot (679)](https://github.com/sisby-folk/antique-atlas/assets/106894328/abdba31e-ad64-4969-a1bf-0f561e70e797)
![Screenshot (675)](https://github.com/sisby-folk/antique-atlas/assets/106894328/d086fe4d-8e16-48a7-8cc6-cac1878323cb)
![Screenshot (676)](https://github.com/sisby-folk/antique-atlas/assets/106894328/ed35e674-8cce-4ba8-919c-91374154bfc4)

**Comment by sleepingdragoninn** [comment]
Yep, some of the few bits of code we haven't rewritten in AA4 so far is the GUI component system which has a very crusty architecture - including reimplementing how tooltips are drawn. Don't need that in 1.20, so we'll toss it out and that'll fix this.

**Comment by sleepingdragoninn** [comment]
should be fixed in 2.7.3, let me know
