### ISSUE TITLE
not functioning on forge

### ISSUE THREAD

**Issue by NachoWarlock** [sleepingdragoninn/antique-atlas#108]
If the fabric API is required how is this supposed to work on forge. game keeps not loading the latest version.

**Comment by sleepingdragoninn** [comment]
> Requires [Connector](https://modrinth.com/mod/connector) and [FFAPI](https://modrinth.com/mod/forgified-fabric-api) on forge.

**Comment by sleepingdragoninn** [comment]
sorry about this one! modrinth doesn't let us specify loader-specific deps
