### ISSUE TITLE
Servers with multiple instances of each dimension cause problems

### ISSUE THREAD

**Issue by arturamiryan** [sleepingdragoninn/antique-atlas#118]
Dimensions are supported, of course, but on many servers there is a lot of overworlds and nethers and ends. Currently working like this: after adding on one dimension the same marks are appear on the map in different world, but same dimension. 

Sorry, if already requested.

**Comment by sleepingdragoninn** [comment]
I've never seen an example of this - can you provide more information?

**Comment by sleepingdragoninn** [comment]
closing as stale - if anyone has an example of this and an idea of how to differentiate between each "copy dimension" on the client let me know.
