### ISSUE TITLE
Scrolling map markers broken in 2.7.3+

### ISSUE THREAD

**Issue by murphy-slaw** [sleepingdragoninn/antique-atlas#119]
After upgrading to 2.8.0 from 2.7.2, there are no longer scroll arrows on the marker selection screen:

![2024-05-25_21 39 05](https://github.com/sisby-folk/antique-atlas/assets/757734/e8a7bb9f-6b7a-4484-aea4-1705ead870b9)

The scroll wheel doesn't work either.

I downgraded to 2.7.3 but the problem remained. Downgrading to 2.7.2 restored the scrolling functionality.

**Comment by murphy-slaw** [comment]
Confirmed on Minecraft 1.20.1, Fabric 0.15.11,  no other mods besides fabric-api.

**Comment by sleepingdragoninn** [comment]
ah the scroll component must rely on odd behaviour we removed in that patch - we'll see about fixing it so that it works without it in a hotfix.
