### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Rebel459** [sleepingdragoninn/antique-atlas#12]
[crash-2024-01-10_13.49.06-client.txt](https://github.com/sisby-folk/antique-atlas/files/13882335/crash-2024-01-10_13.49.06-client.txt)
Crashes with my fabric 1.20.1 modpack instance. Submitting the issue now just to get this out there, but will likely troubleshoot to find the mod conflict later.

**Comment by Rebel459** [comment]
Update: crashes on its own with just the latest fabric api and loader on 1.20.1

**Comment by Aquaeyes** [comment]
I believe it's because it may be missing Kaleido - installing a mod that has it as a workaround may work in the meantime (Euphonium, for example)

**Comment by Rebel459** [comment]
Will do. May just override the jar for now as I’ve already got charmonium, and then will update the mod whenever this is fixed. Thanks for the help

**Comment by Rebel459** [comment]
When it says breaking changes will happen with 2.x, does that mean breaking as in you’d lose your items of breaking as in it would break your entire world save?

**Comment by IvqryDev** [comment]
Could anyone link the Kaleido mod for fabric 1.20.1? i cant find it. or if theres another mod i should use id like to know

**Comment by Rebel459** [comment]
As the person above said, it's bundled with other mods such as Euphonium

**Comment by Rebel459** [comment]
Update: swingthrough's kaleido is not up-to-date enough to work but Euphonium's is (ripped it from the jar)
An official Antique Atlas 4 inclusion/fix would be greatly appreciated so as to allow me to override it into the curseforge port of my modpack too

**Comment by sleepingdragoninn** [comment]
yep can do, it'll be up in a couple of days when I'm back from our trip

It's an easy mistake to make due to our dev setup lol, it's happened before

**Comment by Rebel459** [comment]
Thank you!

**Comment by Rebel459** [comment]
@sisby-folk I've also noticed, with 1.0.0 installed and Kaleido ripped from Euphonium, the Atlas does not appear in the creative inventory nor JEI and I cannot /give it to myself - is this another issue?

**Comment by sleepingdragoninn** [comment]
this is intended - please read the mod description

**Comment by Rebel459** [comment]
Sorry, my bad for the misunderstanding. I was under the impression that only 0.8 and 0.9 were itemless. Is there any chance we’ll see an item-based port at some point in the future?

**Comment by sleepingdragoninn** [comment]
You can see them in the present! We started this project by making the 1.19 and 1.20 PRs to the original project - there are a few github releases for them listed as antique atlas 8.0 and 9.0 - we just aren't professing further with them.

**Comment by Rebel459** [comment]
Thanks! Wasn’t aware of that - are they stable or do they still need work in order to function?
Would rather use the item version in my pack, else will have to go with the current itemless one.

**Comment by sleepingdragoninn** [comment]
they work just fine - I'm not sure if the 1.20 one is missing the latest bug fix with placing markers, but we can make a release for that if needed.

**Comment by Rebel459** [comment]
Thank you once more! Antique Atlases is truly the best vanilla+ navigation/map mod, the time you’ve spent porting and updating it is greatly appreciated

**Comment by sleepingdragoninn** [comment]
fixed in 1.0.1
