### ISSUE TITLE
After rejoining a server modded biomes show up as "?"

### ISSUE THREAD

**Issue by ItzLucaGER** [sleepingdragoninn/antique-atlas#123]
So I have a modded server with Regions Unexplored and if the player has not been on the server before the atlas shows the biomes normally but after a rejoin some of the RU biomes show up like this

Fabric Loader 0.15.11
Version is 1.20.1
AA version is 2.8.1
Surveyor Version on client and server is 0.5.0

Note: Client has AA and Surveyor Framework, server only has Surveyor. 
![image](https://github.com/sisby-folk/antique-atlas/assets/114831048/03b54af3-6460-4c62-9af1-5272725d81c0)

**Comment by ItzLucaGER** [comment]
Seems to work fine in singleplayer with the same world. Weird

**Comment by ItzLucaGER** [comment]
Adding AA to the server didn't change anything, just thought Id try that

**Comment by ItzLucaGER** [comment]
Another thing to note: It only shows the ? around the spawn. The same biomes are a few blocks further and just show normally on the atlas.
![image](https://github.com/sisby-folk/antique-atlas/assets/114831048/6d94b172-af92-49bc-b16d-0a1fd83f30bd)
This is both the same biome but for whatever reason it looks like this 
(edit: when rejoining all the Regions Unexplored biomes become ?. When they get loaded on the Atlas for the first time they look normal, rejoining turns them all into ?)


After deleting the surveyor data on the client and rejoining it looks fine. But only until you rejoin again
![image](https://github.com/sisby-folk/antique-atlas/assets/114831048/72b1351d-7fd0-46a2-b498-f40e545e945a)

**Comment by sleepingdragoninn** [comment]
sounds like some kind of race condition between biome tags loading and tiles loading - can you send your client logs/latest.log via https://mclo.gs/ ? 

Also please check if the issue sticks with specific save data, even after completely closing and reopening the game - if that's the case, send me a zipped copy of data/surveyor and cite a chunk coordinate that appears as ? (use debug mode in the config)

**Comment by ItzLucaGER** [comment]
I closed and re-opened the game several times. Here is the log, I will do the other thing right now. https://mclo.gs/djliFOq

**Comment by ItzLucaGER** [comment]
Do you want me to turn on the "debugRender" option?

**Comment by sleepingdragoninn** [comment]
That will help you get a sample chunk coordinate, yep.

**Comment by ItzLucaGER** [comment]
[surveyor.zip](https://github.com/user-attachments/files/15507554/surveyor.zip)
Just picked a random chunk: 8,3 (128,51)

**Comment by ItzLucaGER** [comment]
Also I noticed when I restart the game and join for the first time it also renders normally, only after rejoining it happens.

**Comment by sleepingdragoninn** [comment]
race issue: 

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/cd22eed3-0e32-4247-bade-ca807b0f9968)

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/f48eea21-9c7f-4a31-a171-e099b9ea38cd)

tiles are loading before fallback biomes are set - this means that something in your modpack is causing tags to be serialized way later than they should (REI maybe?)

**Comment by ItzLucaGER** [comment]
REI is on the server and client, do I have to remove it on both to test it?

**Comment by sleepingdragoninn** [comment]
worth a try, but honestly it's just a shot in the dark. I'll see if there might be some way to prevent atlas from loading before tags are in properly.

**Comment by ItzLucaGER** [comment]
I'll try and send the log again in a minute

**Comment by ItzLucaGER** [comment]
https://mclo.gs/eGfj9CS
welp, its not REI

**Comment by sleepingdragoninn** [comment]
It was REI - that log indicates that the tag-lag is gone - another reason to recommend EMI i'll remember lol. Still getting ?s though?

**Comment by ItzLucaGER** [comment]
Yes Im still getting the ?s, thats what I meant, my bad

**Comment by sleepingdragoninn** [comment]
here's a version that holds off on generating any actual tiles until tags have been loaded [antique-atlas-2.8.2+1.20.jar.zip](https://github.com/user-attachments/files/15507577/antique-atlas-2.8.2%2B1.20.jar.zip) - give that a shot.

**Comment by ItzLucaGER** [comment]
Will do, brb lol

**Comment by ItzLucaGER** [comment]
https://mclo.gs/9TMVOVr Works with REI, not getting any ?s anymore :D But since I am using the mod in a modpack on Modrinth I am gonna need permission to use this file, since this version isn't on Modrinth as far as I can see

**Comment by ItzLucaGER** [comment]
Otherwise I can also switch to JEI or EMI if that will fix it

**Comment by sleepingdragoninn** [comment]
Hmm no I was mistaken - looks like your first connect didn't have the tag-lag, but the second one does? still might be another mod causing it, but regardless the fix will apply. Thanks for the help! that's published on modrinth now.

I do highly recommend EMI over REI in general! do look into it! but that's not related to this bug anymore :P

**Comment by ItzLucaGER** [comment]
no thank YOU for the help. Glad its fixed so fast :)

**Comment by ItzLucaGER** [comment]
also I just switched out REI for EMI and oh my god this is so much better xD
