### ISSUE TITLE
Mod does not work

### ISSUE THREAD

**Issue by AronV4** [sleepingdragoninn/antique-atlas#124]
I have curseforge and I try to add this mod for forge 1.20.1 and it doesn't work.

**Comment by AronV4** [comment]
In the description it mentions that it works for both fabric and forge.

**Comment by sleepingdragoninn** [comment]
> Requires [Connector](https://modrinth.com/mod/connector) and [FFAPI](https://modrinth.com/mod/forgified-fabric-api) on forge.

duplicate of #120 and #108
