### ISSUE TITLE
Map progress is wiped on join sometimes

### ISSUE THREAD

**Issue by crabinpenguin** [sleepingdragoninn/antique-atlas#13]
sometimes when I relaunch my game the map is reset. no exploration past the chunks loaded around me, and no waypoints that I previously placed

**Comment by sleepingdragoninn** [comment]
Next time this happens, can you upload a copy of your `logs/latest.log` to https://mclo.gs/ before relaunching the game?

This is an upstream bug that occurred in the original port if i remember right, and I'm not 100% on what causes it.

**Comment by crabinpenguin** [comment]
Thanks for getting back to me so quickly, next time I launch the game and my map progress is wiped I'll upload the logs for you!

**Comment by crabinpenguin** [comment]
Okay, my game crashed and when i launched it again the progress was wiped. I've uploaded the latest log.

**Comment by sleepingdragoninn** [comment]
can you send the link?

**Comment by crabinpenguin** [comment]
https://mclo.gs/hOr1sqM

**Comment by sleepingdragoninn** [comment]
Continued in #17
