### ISSUE TITLE
Farsight prevents map from updating correctly

### ISSUE THREAD

**Issue by PanIntegrah** [sleepingdragoninn/antique-atlas#131]
It works in singleplayer. Map doesn't update until I disconnect.
Forge: 1.20.1 47.3.0

[Server log](https://mclo.gs/6eN9hGB)

[Client log](https://mclo.gs/s4Dyx4g)

![image](https://github.com/sisby-folk/antique-atlas/assets/42538693/a23f9020-8b61-43da-bb59-4a88f901e6cf)

**Comment by sleepingdragoninn** [comment]
Does this issue still occur if you spin up a fresh forge 47.1.3 instance and server with just antique atlas?

**Comment by PanIntegrah** [comment]
Let me try, but it would be nice if it worked with 47.3.0 or a bit older, because many mods on this modpack require at least 47.2+

**Comment by sleepingdragoninn** [comment]
We don't have a specific requirement for a forge version, but Connector specifies 47.1.3 - so if something's broken, it could be related.

**Comment by PanIntegrah** [comment]
Yes, can confirm, it works with fresh install in 47.1.3. Is there a way I can debug or try to fix it in 47.2-47.3?

**Comment by sleepingdragoninn** [comment]
in practice, you need to find exactly where that breaks - so start by changing to 47.3 and see if that still works, then if it does, you'll have to progressively add your mod list until it breaks

**Comment by PanIntegrah** [comment]
Okay, it works in fresh 47.3.0, so probably it's an external problem. Well, time to take like 2 hours adding mods until I find what breaks it!

~~Thanks for the help, will edit this comment with the faulty mod doing this.~~

The impostor is [Farsight](https://www.curseforge.com/minecraft/mc-mods/farsight), both client and server.

**Comment by sleepingdragoninn** [comment]
Thank you! I believe this is just farsight preventing the expected chunk send method from running that surveyor watches. Odd though!
