### ISSUE TITLE
Overworld shows up in Nether

### ISSUE THREAD

**Issue by ItzLucaGER** [sleepingdragoninn/antique-atlas#132]
So Im not sure if its intended but I entered the Nether and the atlas basically just overwrites the overworld map with the nether chunks and even overworld markers show up here. 

The 2 lower markers are from the overworld
![image](https://github.com/sisby-folk/antique-atlas/assets/114831048/7e983264-9ff1-489d-ad82-1a603d1063cd)

Newest version for 1.20.1

**Comment by sleepingdragoninn** [comment]
Immersive portals?

Otherwise, feel free to post your log/latest.log to https://mclo.gs

**Comment by ItzLucaGER** [comment]
No immersive portals, give me one second to upload the log

**Comment by ItzLucaGER** [comment]
https://mclo.gs/9ZbsE4r

When I logged in I already was in the nether this time

**Comment by sleepingdragoninn** [comment]
does this occur on a fresh fabric 1.20.1 instance with just antique atlas?

If not, you'll need to add your mods slowly until you find where it breaks. I'd start with c2me, that's the only thing I can see that's related.

**Comment by ItzLucaGER** [comment]
Let me try, should sodium/embeddium be fine? I kinda need it for performance lol

**Comment by sleepingdragoninn** [comment]
point is for you to find out what exactly isn't fine - doubt it'll be sodium though, we'd have much more complaints about this if so :P

**Comment by sleepingdragoninn** [comment]
What I specifically expect is a mod that is breaking the vanilla process of joining and leaving worlds - maybe a dimension mod, or something that does heavy caching. that's why immersive portals was the first bet.

**Comment by ItzLucaGER** [comment]
Works fine with a fresh instance with Sodium and AA. Keep in mind that I can only test this on a singleplayer world. When I opened this issue I was playing on a server

**Comment by ItzLucaGER** [comment]
I'll test it with c2me now

**Comment by ItzLucaGER** [comment]
Works fine with that too, actually I should first test if the issue even persists in singleplayer when using the instance with all the mods I used before lmao

**Comment by ItzLucaGER** [comment]
It actually crashes in singleplayer lol. Seems to be AA related?
https://mclo.gs/OtPRPVx

**Comment by sleepingdragoninn** [comment]
the two issues probably have the same root cause. at least there's something easier to detect now. I could put in a crash guard, but I don't think that would do you any good - the mod attempting to load null chunks indicates a mod very much is causing an issue.

**Comment by ItzLucaGER** [comment]
Alrighty, I'll keep removing/adding some and see what causes it

**Comment by ItzLucaGER** [comment]
Seems like it is caused by Mythic Metals or its dependency Alloy Forgery

**Comment by ItzLucaGER** [comment]
Well it didnt crash but just stopped responding and I had to restart my PC lol

**Comment by ItzLucaGER** [comment]
With all mods expect mythic metals the nether loads just fine. I'll try a fresh instance with AA, Mythic metals, Alloy Forgery and Sodium now

**Comment by ItzLucaGER** [comment]
Fuck that again just works normally? So its a incompatibility between Mythic Metals and something else? Im so confused

**Comment by sleepingdragoninn** [comment]
Yeah you want the minimum amount of mods that can cause the crash.

**Comment by ItzLucaGER** [comment]
Yep thats gonna take a while, might be a few hours until I find anything since its almost 3 AM here :p

**Comment by ItzLucaGER** [comment]
Alright I tried it with a different world AND all the mods and it.. just... works??? Could it be related to the world Im using on the server? I just used the seed from the server to test in singleplayer

**Comment by ItzLucaGER** [comment]
Yep, with the seed 1054810477605054856 it crashes. https://mclo.gs/gJwUhZt
Exact same error as before. So back to testing 
This feels very cursed

**Comment by ItzLucaGER** [comment]
Without mythic metals I can get into the Nether without it crashing on this seed. So now I will do what you said earlier and remove as many mods as I can while still getting the crash lol

**Comment by ItzLucaGER** [comment]
Oh, I think I already found the mod clashing with Mythic Metals and AA. Its Regions Unexplored. With mythic and no RU it works just fine on that seed.

**Comment by sleepingdragoninn** [comment]
with the minimum required to crash, can you post your logs/latest.log for a run where you just start it and immediately crash it?

Regions unexplored is an ARR biome overhaul so my guess would be it specifically, but it might be a specific one of their biomes etc.

**Comment by ItzLucaGER** [comment]
Im still trying to figure out what the minimum is since with these it again just works fine. Im slowly adding more back to find the exact issue 
![image](https://github.com/sisby-folk/antique-atlas/assets/114831048/bbfabedb-55e9-4045-abd1-c201c8412e3f)

**Comment by ItzLucaGER** [comment]
When using all of the mods Removing either RU or Mythic fixes it though. So Im very confused

**Comment by ItzLucaGER** [comment]
I genuinely cant find what mod is causing it. I slowly added them all back and it works fine again. Man Im confused

**Comment by ItzLucaGER** [comment]
Yeah with all the mods in a different instance it works fine. Might be something in my normal instance thats causing it. Either way Im off to bed for today so if there's news I'll take a bit to reply :)

**Comment by ItzLucaGER** [comment]
How would I go about resetting all the AA data on my client? Then I can try that on my main instance tomorrow

**Comment by sleepingdragoninn** [comment]
for singleplayer it's in /data/ for each dimension in the save. for multiplayer it's /data/ in the instance root

**Comment by ItzLucaGER** [comment]
So on the server nothing would have to be deleted?

**Comment by sleepingdragoninn** [comment]
server same as singleplayer - world/data, world/dim-1/data etc

**Comment by ItzLucaGER** [comment]
I commented on the wrong issue first, oops. Anyway, after deleting the surveyor data of the server from my client and rejoining it works just fine, maps looks normal too. Im not even sure what happened

**Comment by ItzLucaGER** [comment]
I guess this can be closed. I think the issue appeared because when I was developing my modpack I tested a bunch of things and mods with the same world, basically creating it over and over to see if everything works. I guess that messed with it somehow?
