### ISSUE TITLE
game intermittantly crashes on joining server

### ISSUE THREAD

**Issue by annahla** [sleepingdragoninn/antique-atlas#134]
deleting the data/surveyor folder temporarily fixes the issue, but it always comes back eventually. once it comes back, it doesn't go away until you delete the folder.

crash report: [crash-2024-06-12_23.56.10-client.txt](https://github.com/user-attachments/files/15812457/crash-2024-06-12_23.56.10-client.txt)

**Comment by sleepingdragoninn** [comment]
Out of curiosity, can you think of any reason your game might think that there are 42160 unique biomes in a 32x32 chunk area?

Anyway upload your logs/latest.log to https://mclo.gs/ on a run that causes a crash and we'll have a closer look.

**Comment by annahla** [comment]
what's that, 40 biomes a chunk? hot fuckin damn
of note is the number isn't always the same
but uhh
yeah no clue

latest.log: https://mclo.gs/Fx2N4rs
debug.log (just in case): https://mclo.gs/BzZHqgi

**Comment by sleepingdragoninn** [comment]
so my guess here is that whatever hash we're using to construct the biome palette is completely exploding and individual instances of the same biome are being added to the palette seperately. This also means your surveyor save files are probably horrendously large - could you send me a copy of one of your chunk saves? (should start with c and then be numbers) - you can zip it to send it.

If I was to guess the interfering mod that may be causing this - c2me, distant horizons, bclib, all are possible, but I'm not certain - it could be something totally different, like a biome mod mixing into a getter in a weird way.

**Comment by annahla** [comment]
if you know what file/method's likely the culprit I can grep through all my mod files to find which one mixes into it?
out of curiousity though, what values are hashed for the palette?

but yeah of those you listed I have bclib
here's the biggest chunk dat: 
[c.-1.0.dat.zip](https://github.com/user-attachments/files/15822673/c.-1.0.dat.zip)
1.1mb uncompressed, but there's a ton of others in the 100s of kbs

**Comment by sleepingdragoninn** [comment]
as suspected:

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/1242bebc-9447-40bb-82c3-7bb6b6d8003c)

**Comment by sleepingdragoninn** [comment]
So I think i'm gonna fix this on the surveyor end by relying on the raw biome IDs from the registry in my authoritative palette, which can't be tampered with in the same way as biome objects. I checked and yeah, the palette object we were using relies on refchecks - so one of your mods is causing different instances of the same biome to be passed in.

Super interesting honestly and i'd be intrigued to know who so they can be informed of their accidental heinous deeds, but yeah we'll fix this on our end regardless.

If you're equally curious, i can send you a version of the mod that makes it clear whether this is happening as soon as you load into the world so you can bisect/grep/etc.

**Comment by sleepingdragoninn** [comment]
here's your tattletale version:

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/36c0e0cc-b3bc-4185-945b-c4d556eb04ff)
[surveyor-0.5.0+1.20.zip](https://github.com/user-attachments/files/15830545/surveyor-0.5.0%2B1.20.zip)

on a launcher like prism that should be very visible using the live log viewer as soon as you pause.

**Comment by annahla** [comment]
oh my fucking god
I got a few ideas about what mod's fucking then; I'll check w the tattletale version
thanks :)

**Comment by annahla** [comment]
aaaand it was none of my ideas

(did also check the c.dats to make sure there wasn't any like, levels of duplication under 1000)

though I do wonder if it could be a dedicated server specific issue? been testing on singleplayer.
though I don't know enough abt how minecraft gets consistent refs to biome resourcelocs, so idk

**Comment by sleepingdragoninn** [comment]
it could be multiplayer related? restoring chunks from the server is a unique process that requires tampering with the biome palette.

**Comment by sleepingdragoninn** [comment]
Hello! Here we are post-refactor: 
[surveyor-0.5.1+1.20.zip](https://github.com/user-attachments/files/15831556/surveyor-0.5.1%2B1.20.zip)

Surveyor now uses biome and block raw IDs as the authority for the palette, meaning that checking for duplicates is done using their raw IDs, which are ints - so less possibility of mods interfering. It's possible this will surface new crashes in other people's instances, but they should be at least more obvious.

Try this out in your real crashing instance with all the mods - both client and server side.

**Comment by annahla** [comment]
oh yeah it's gotta be multiplayer related; just checked the (old) .dats serverside, no duplicationf

alright, tried out the post-refactor, it's all good!! no duplication anymore
still got some other bugs(?) I thought were related (map data not always filling in, though if map data's generated between ticks it's just that my server's hardware is ass)
if that is an actual bug I'll submit a separate report though
thank yalls so much!!!!!!

**Comment by sleepingdragoninn** [comment]
As long as the other bugs aren't _new_ i'm happy with that ahahah

**Comment by sleepingdragoninn** [comment]
Released as 0.5.1 now - we'll hotfix atlas to have it builtin soon enough.

**Comment by annahla** [comment]
lkdsaj yep no new issues
thanks again!!!
