### ISSUE TITLE
Renamed book as Atlas book

### ISSUE THREAD

**Issue by deivpaukst** [sleepingdragoninn/antique-atlas#136]
So I've been thinking, since the mod is client side only (which is _soo_ cool!), it could be possible to readd the Atlas book as an item too if a normal book, renamed in an anvil to like "Antique Atlas" could then, by the mod, be used as the Atlas for the player using the mod, but just a normal book for everyone else.
Just food for thought.

**Comment by sleepingdragoninn** [comment]
solid idea! could you add this as a note to #86? this method could be a good way to kickstart that one.
