### ISSUE TITLE
Crash on entering Nether

### ISSUE THREAD

**Issue by ErrorReportah** [sleepingdragoninn/antique-atlas#138]
As the title says, crashes near instantly once going through the portal. 

Clean install of just Antique Atlas, Surveyor Framework, and Fabric API

https://mclo.gs/VDckRbm

**Comment by ErrorReportah** [comment]
Downgraded Surveyor Map Framework from 0.5.1 to 0.5.0 and crash stops happening.

**Comment by GingerPopper** [comment]
Same problem, can confirm that downgrading Surveyor to 5.0 fixes the issue.

**Comment by sleepingdragoninn** [comment]
Shoutouts to everyone who manually installs surveyor alongside antique atlas for being convenient canaries for changes :joy:

Thanks for the clean log! We know exactly what change this crash is related to, so we'll just tinker with it from here.

**Comment by sleepingdragoninn** [comment]
Should be fixed in 2.9.1, the issue was much funnier than we expected, just a typo.
