### ISSUE TITLE
Mapp gets cleared out after death

### ISSUE THREAD

**Issue by iustin94** [sleepingdragoninn/antique-atlas#139]
I noticed a bug where in my main world when I die, all the explored map is cleared out, however the markers I put stay behind. I tested this out on a clean instance with no other mods and it does not reproduce. I also tested it on the same instance with a new world and it also did not reproduce. 

Is there a specific condition that makes the map clear out after death?

**Comment by iustin94** [comment]
After looking at it a big, it looks like it's not always that the map gets cleared out. I haven't found yet why it happens or when,

**Comment by sleepingdragoninn** [comment]
Instances of map clearing are usually related to auth failing / the player's UUID changing. Assuming this is in singleplayer, I think this should be resolved with https://github.com/sisby-folk/surveyor/issues/22

**Comment by iustin94** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/13846875/2a6aa974-8242-4a8c-b997-be0ee3fda58d)

**Comment by iustin94** [comment]
@sisby-folk Is there a way I can verify if that's what causes it for me? Can I somehow forcefully change my UUID or cause the authenticaiton to fail?

**Comment by iustin94** [comment]
would there also be any chance to recover all the data? It's quite annoying that this happens and if can know what the issue is I can make a PR with the fix for it :)

**Comment by sleepingdragoninn** [comment]
if this is singleplayer, turn on shareAllTerrain in surveyor.toml - that'll work around it for now.

**Comment by iustin94** [comment]
That seems to have fixed some of it, and returned some of the lost map back. In adition, I enabled all of the parameters in the file, and now I also get on the map structures and vilages which I had seen from a distance, but they did not show on the map, or even some that I was inside of and still did not show :)

**Comment by sleepingdragoninn** [comment]
should be fixed in 2.9.6
