### ISSUE TITLE
Bring more attention to Forge deps in mod page description

### ISSUE THREAD

**Issue by Kira-Hudson** [sleepingdragoninn/antique-atlas#145]
So I spent a while trying to figure out how to get AA4 to work on 1.20.1 Forge, on Modrinth, only to, after some research, discover the answer was stated on the mod page.

![image](https://github.com/sisby-folk/antique-atlas/assets/123496245/6a67fd82-2a96-4b0d-a10e-5e6ac1524448)

However, the disclaimer is just half a line of some pretty condensed text which seems to me a little too obscure to be read by the average user, and could easily be missed when skimming over the page briefly, as I'm sure many do (though I may of course be wrong).

![image](https://github.com/sisby-folk/antique-atlas/assets/123496245/b32d5a01-2223-4e6e-b64d-f5666a804c7b)

I would propose that more attention is called to this dependency, even if that just means making the text bold, "**Requires [Connector](https://modrinth.com/mod/connector) and [FFAPI](https://modrinth.com/mod/forgified-fabric-api) on forge.**", for example.

I think you'll agree that
![image](https://github.com/sisby-folk/antique-atlas/assets/123496245/8d7e5eb6-c855-44a1-bd36-4def52ac09cf)
stands out more than
![image](https://github.com/sisby-folk/antique-atlas/assets/123496245/85763f53-00b5-4020-be7e-0e7ebb126849)

I understand there may be some other issue I'm not considering that might prevent this, like specific styles and formatting you'd like to stick to, but I would urge you to consider it anyway. Thank you for your time.

Related issues: #108, #120 and #124

_(P.S., "and less!" lol)_

**Comment by sleepingdragoninn** [comment]
fair enough!
