### ISSUE TITLE
Any Plans to add compatibility for Neoforge?

### ISSUE THREAD

**Issue by CharlesBuckington** [sleepingdragoninn/antique-atlas#152]
The title pretty much says it all. This will literally be the dealbreaker if Ill switch to neoforge or stay with a fabric pack haha

**Comment by sleepingdragoninn** [comment]
Seems inevitable, we just might not be the ones to do the port - similar to our 1.19.2 and 1.18.2 ports it might wait until a few more things have polished out. 

If connector does 1.21 neo, that'll give you it for free, but i've heard no word of that yet. 

on 1.20.1 you can use connector on latest neo already.

**Comment by CharlesBuckington** [comment]
Thanks for the reply and the connector tip, appreciate you guys <3
