### ISSUE TITLE
Mod not behaving 

### ISSUE THREAD

**Issue by Arch23-tech** [sleepingdragoninn/antique-atlas#155]
When used on forge the mod not shown entirely in mod menu, it does not behave or work either so no maps available while playing.

**Comment by sleepingdragoninn** [comment]
this should be fixed since 2.9.4

**Comment by Arch23-tech** [comment]
Sorry 😞 ... I think I downloaded a bit older version due to me first time
trying the mod... sorry for the miss-reporting

**Comment by sleepingdragoninn** [comment]
all good! we only just remembered the trick for making dependencies appear on forge safely.
