### ISSUE TITLE
Map Data Removed

### ISSUE THREAD

**Issue by ShobeShoob** [sleepingdragoninn/antique-atlas#158]
I'm using version 2.9.8 with Surveyor 0.6.2.
Every time I keep joining a multiplayer server and loading my map through exploration + adding markers, once I leave and rejoin it all gets erased and I'm just left with a blank chunk where I'm standing. I have no idea what to do.

**Comment by sleepingdragoninn** [comment]
vanilla or surveyor server? 1.20 or 1.21?

**Comment by sleepingdragoninn** [comment]
1.21 client data not saving issue fixed in .9
