### ISSUE TITLE
Crash after trying to erase a waypoint

### ISSUE THREAD

**Issue by TheLegendofSaram** [sleepingdragoninn/antique-atlas#159]
The map works great but consistenly after erasing a waypoint the game crashes. Here is the crash log
BTW.
Im using the lastest version of Surveyor Map Framework and Antique Atlas 4 for 1.20.1 fabric (Loader 0.15.11)
[crash-2024-07-06_19.43.38-client.txt](https://github.com/user-attachments/files/16117626/crash-2024-07-06_19.43.38-client.txt)

**Comment by YOUNIN15** [comment]
The same thing happens to me, it doesn't let me add a waypoint. I use the same version as you.

**Comment by sleepingdragoninn** [comment]
isolated, should get a fix out today.

**Comment by YOUNIN15** [comment]
Use the previous version 2.9.8 in that works well add and delete waypoint, apparently the error is in the latest version of Surveyor eyo, I tried several previous versions with the latest version of Surveyor and all crashes when trying to delete a waypoint, but if you use a version prior to 2.9.8 will work, surely installing a previous version of Surveyor fix the error too.

So you can use 2.9.8, if you have Surveyor separately remove it or downgrade the version.

**Comment by SplendidAlakey** [comment]
Downgrading erased a lot of my map progress and removed some markers, don't recommend doing so.

**Comment by sleepingdragoninn** [comment]
should be fixed in 2.9.10 - gave it a decent smoke test in dev, hopefully theres no edge cases with the new config - thanks!
