### ISSUE TITLE
Atlas is entirely question marks with Remove Reloading Screen

### ISSUE THREAD

**Issue by HollyBlocky** [sleepingdragoninn/antique-atlas#161]
Tested in both singleplayer and multiplayer. Tested in environments of: creation of new worlds, playing existing worlds where previous versions of Antique Atlas worked, playing multiplayer servers where previous versions of Antique Atlas worked. I also previously deleted modified config files of Surveyor and of the Antique Atlas before installing version 2.9.10. (I was previously on 2.9.5 if I remember right)

In Singleplayer, I'm defined as "???" on the Antique Atlas, and no tiles of any biome seem to exist regardless of if I'm in singleplayer or multiplayer. Seems like biome data just doesn't exist at all.

![javaw_LrcDMUqBuj](https://github.com/sisby-folk/antique-atlas/assets/78760703/fb4ce45a-9102-4d72-a746-bce9213e5f73)
[latest.log](https://github.com/user-attachments/files/16119635/latest.log)

**Comment by HollyBlocky** [comment]
In the screenshot, I'm standing in a snowy plains by a river, a pond, and a cave. The latest.log file says more.

**Comment by HollyBlocky** [comment]
Found it. It was a mod incompatibility with the [Remove Reloading Screen mod](https://modrinth.com/mod/rrls) which I added sometime after my initial use of Antique Atlas.

**Comment by sleepingdragoninn** [comment]
thanks for the report!
