### ISSUE TITLE
The atlas does not update player position

### ISSUE THREAD

**Issue by DaPuffer** [sleepingdragoninn/antique-atlas#162]
Atlas version: 2.9.10+1.20
Mc version:1.20.1
Connector version:1.0.0-beta.44+1.20.1
Forge version:47.1.3
https://github.com/sisby-folk/antique-atlas/assets/132820752/3dc38ff6-01f9-43f6-b426-23bf9845415d
[latest.log](https://github.com/user-attachments/files/16128388/latest.log)
Pressing escape to save the world updates the player's position once,and turns the player marker grey.
![image](https://github.com/sisby-folk/antique-atlas/assets/132820752/0c05ad3c-bbe2-4de5-8ff6-2ad349c9d96c)

**Comment by DaPuffer** [comment]
Additional info: this issue did not exist before 2.9.7. The atlas updates the player's position normally in version 2.9.6

**Comment by sleepingdragoninn** [comment]
yep, seems to only affect singleplayer - i'll take a look.

**Comment by sleepingdragoninn** [comment]
should be fixed in .11

**Comment by GhostGuy9** [comment]
This issue sadly came back in current version, 2.11.2 effecting singleplayer again

**Comment by GhostGuy9** [comment]
This issue sadly came back in current version, 2.11.2 effecting singleplayer again
