### ISSUE TITLE
Cannot invoke "net.minecraft.server.level.ServerPlayer.m_20194_()" because "player" is null

### ISSUE THREAD

**Issue by Zidiath** [sleepingdragoninn/antique-atlas#163]
Minecraft 1.20.1
NeoForge 47.1.106

antique-atlas-2.9.11+1.20

Can reproduce when going through a nether portal for the first time (generating a brand new one in the nether). I will start stripping mods out to see if I have a conflict somewhere.

[crash-2024-07-08_15.33.19-server.txt](https://github.com/user-attachments/files/16133790/crash-2024-07-08_15.33.19-server.txt)
[latest.log](https://github.com/user-attachments/files/16133793/latest.log)

**Comment by sleepingdragoninn** [comment]
minor typo on our end, fixed in surveyor 0.6.11
