### ISSUE TITLE
Crashes everytime I get into a dimension (nether)

### ISSUE THREAD

**Issue by ItzBurning2023** [sleepingdragoninn/antique-atlas#164]
I'm not sure if the issue is Sinytra Connector or Antique Atlas but every time I get into a portal like the nether portal my game just closes and crashes immediately. 
Here is the crash report: 
[crash-2024-07-09_12.33.02-server.txt](https://github.com/user-attachments/files/16146621/crash-2024-07-09_12.33.02-server.txt)

**Comment by sleepingdragoninn** [comment]
crash fixed on latest
