### ISSUE TITLE
Forge coding

### ISSUE THREAD

**Issue by Arch23-tech** [sleepingdragoninn/antique-atlas#166]
Mr. Sisby folk I don't want you take a misunderstanding approach towards my suggestion....

You are a well skilled Modder, I just realized the newly updated forge versions require (FFAPI & Connector) in order to work. 
So that's not the best thing for us (forge users), because those two mods not always working or sometimes cause significant crashes, even conflict with other existing mods .....

So I hope if you could port or build a forge port of this unique mod from ground up, without the need to use (FFAPI & Connector) for antique atlas base mod ...

Thank you for your efforts and for this piece of art.

**Comment by sleepingdragoninn** [comment]
we'll be considering a native neo port on 1.21 at some point! and someone might step up to do a forge 1.18/1.19 backport, seeing as there's no connector there either.
