### ISSUE TITLE
Palette index crash on world load (modpack)

### ISSUE THREAD

**Issue by AACJR** [sleepingdragoninn/antique-atlas#173]
Minecraft 1.20.1
Neoforge 47.1.106
Latest Antique Atlas/Surveyor (also using surveystones)
 
Game seems to crash on loading any world
Here is the config and also the full log if needed
[crash-2024-07-17_16.54.54-server.txt](https://github.com/user-attachments/files/16275941/crash-2024-07-17_16.54.54-server.txt)
[2024-07-17-7[1].log](https://github.com/user-attachments/files/16275943/2024-07-17-7.1.log)

**Comment by sleepingdragoninn** [comment]
this is pre 0.5.4 so it's almost certainly fixed by the remapper added then.
