### ISSUE TITLE
Structure without pieces crashes surveyor

### ISSUE THREAD

**Issue by KavisCorea** [sleepingdragoninn/antique-atlas#174]
[crash-2024-07-17_22.41.36-server.txt](https://github.com/user-attachments/files/16278866/crash-2024-07-17_22.41.36-server.txt)

Antique Atlas 2.9.12 | Was using connector since I'm on the Neo/forge modloader 

If there is any more needed information, please let me know!

**Comment by sleepingdragoninn** [comment]
One of your mods adds a structure without any pieces - we'll add a safety check for that.

**Comment by KavisCorea** [comment]
Awesome, thank you!

**Comment by sleepingdragoninn** [comment]
done in surveyor 0.6.18!
