### ISSUE TITLE
Make the mod description more clear

### ISSUE THREAD

**Issue by DefinitelyNotFred** [sleepingdragoninn/antique-atlas#175]
It would be a good idea to update the mod description to make it clear that there is no map item like there was in the old versions of Antique Atlas. I know you have responded to others who were confused about the lack of an actual map item as I was by saying that the description says to "Press [M] at any time to bring up the world map", but this statement does not necessarily mean that there is no map item.

I saw that statement in the description before I downloaded and assumed that it simply meant it would bring up a map that was bigger than a minimap in the corner, or maybe that I could have an atlas item buried in my inventory and still have the map pop up with that key any time after crafting it. Luckily I found those comments you had made to others before I created my own issue about it, but it took a relatively in-depth search on my part to find them.

**Comment by sleepingdragoninn** [comment]
Feel free to propose a specific change to the description.

There are lots of features that Antique Atlas 4 doesn't have (e.g. facebook authentication, a minimap, coconut blocks) that are also not in the description, so i'm unsure how to effectively convey this to people familiar with the original mod without confusing users new to the mod.

**Comment by DefinitelyNotFred** [comment]
Honestly, the one change about how to bring up the map would be good enough. From the players perspective, that is a change to the fundamental way the mod operates, while the other changes are much more secondary and could be more readily understood to be things that were dropped with the rewrite. That's how it worked for me, at least.

Here's how I would redo the description. I reworked the whole main body so I could split the features list into client-side and server-side and move most of the stuff from the end into the rest of the main body. I felt that just having the one line about installing it on the server was rather awkward and that the stuff at the end was better served towards the beginning.  
#   
> #### Antique Atlas 4 is designed to keep you focused on exploring the world around you, _NOT the map!_
>
> Press **[M]** to bring up your atlas map on it's own, stylish GUI screen
>
> Drag the map to pan, scroll to zoom, and use the bookmark buttons to create, remove, or hide waypoints.
>
> ### Features
> - AA4 has _absolutely no items._ This means that you can use it as soon as you load into a world, that you won't ever lose your map, and that you can even use it on servers that don't have AA4 installed!
> - The map is rendered using hand-drawn "tiles" to represent terrain, biomes, and structures.
> - At their smallest, tiles represent an entire chunk, and are only revealed as you find them - no peeking for resources or player bases!
> - Gravestones automatically appear where you die and can have optional flavor text:
> **[Grave Style Euphemisms image]**
> - Markers for waypoints come in a variety of styles:
> **[Marker Styles image]**
>
> ### **Additional Single-player and Server-side Features**
> - Markers are automatically added for notable structures and active nether portals:
> **[Structure Markers image]**
> - Structures only appear on the map after you've looked at them or stood on them in-game:
> **[Structure Discovery gif]**
> - Map exploration can be shared with `/surveyor share [player]` which will also reveal their position on the map:
> **[Map Sharing image]**
> - You can install [Surveyor](https://modrinth.com/mod/surveyor) without AA4 on server installations to enable these features
>
> All of the above is data-driven using resource packs. If you are always using your map as a compass, we recommend trying [PicoHUD](https://modrinth.com/mod/picohud) as well.

**Comment by sleepingdragoninn** [comment]
concise and foolproof, will do.

**Comment by sleepingdragoninn** [comment]
added, revised and reshuffled - description is now shorter, too. Thanks for your contribution!
