### ISSUE TITLE
Store map on-server in-item nbt

### ISSUE THREAD

**Issue by Axosotle** [sleepingdragoninn/antique-atlas#178]
well if in the map can you help to make the map work as an item and also to share the map you don't need to write a command and just connect atlases in the workbench grid.
As I understand for this you need to rewrite the method of saving atlas data each atlas was saved on the server and not on the client.
Also it would be nice if the atlas would be bound not to the player but to the nbt tag of the item.
I understand if you refuse I have little skills to realize all this I have only realized the AtlasID system.
This is all necessary because we want to use your mod in a custom mod build I hope for your understanding.
I'll also leave a link to your AtlasID mod - https://github.com/Axosotle/AntiqueAtlas-LS

**Comment by sleepingdragoninn** [comment]
Hi there! I'd recommend the mod [Antique Atlas](https://modrinth.com/mod/antique-atlas) for this! it has all the features you describe.

**Comment by Axosotle** [comment]
I'm sorry it doesn't work for me because it's not available on the new version and also the problem is that I really like your mod.
