### ISSUE TITLE
Incompatibility with BCLib

### ISSUE THREAD

**Issue by IsaDucko** [sleepingdragoninn/antique-atlas#184]
https://pastebin.com/T5T2prvf
[crash-2024-07-31_15.55.44-client.txt](https://github.com/user-attachments/files/16442771/crash-2024-07-31_15.55.44-client.txt)

Same file
I know suspected mods says BClib and somehow Minecraft, there is no new version of BClib, idk what to do about minecraft, all I know is that i get a -1 (probably) incompatibility error when launching together with Antique Atlas

**Comment by sleepingdragoninn** [comment]
there are a lot of mods here, does this happen with solely bclib and antique atlas? 
if so, does it happen with solely bclib and ffapi/connector?

**Comment by IsaDucko** [comment]
Will check give me a bit

**Comment by IsaDucko** [comment]
https://pastebin.com/3xsUdSHC
only mods are Sinytra connector, Antique Atlas, BCLib and Forgified Fabric API
it only happens when i use Antique Atlas, was able to run purely bclib, connector and api together

do tell me if you notice a mistake with how i tested or want me to try something else
also ty for the fast response

**Comment by sleepingdragoninn** [comment]
there's nothing related to atlas itself in the log - can you try replacing atlas with another connector/ffapi mod ([picohud](https://modrinth.com/mod/picohud)) and find out if the same thing happens?

**Comment by IsaDucko** [comment]
Picohud works, heres an extra message when i start the game
![image](https://github.com/user-attachments/assets/35a376b5-a1c4-471a-b2a2-fb87fef278a1)

**Comment by IsaDucko** [comment]
can i ask which version of forge and sinytra you guys run?

**Comment by sleepingdragoninn** [comment]
connector recommends 47.1.3 - but i've also used latest neoforge. either of these seem to work fine.

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/user-attachments/assets/2dcaa9bc-54fd-4b35-959e-d229eea66280)
can't reproduce.
