### ISSUE TITLE
Why can’t players be given more choices?

### ISSUE THREAD

**Issue by reana-ovo** [sleepingdragoninn/antique-atlas#186]
Why were the atlas item removed, it ruins the immersion of the old versions. I feel like I'm playing two completely different mods. Sharing the map after your adventure, and having a real atlas book makes me feel like I am playing the AA. Now i just feel like this is some resource pack of a random world map mod.
I don't understand why this is happening, and if something was in your plan then will it be much better if clearified in the description?

**Comment by sleepingdragoninn** [comment]
not a valid issue - you're asking for a completely different mod. I'd request a 1.21 port from tyra instead.
