### ISSUE TITLE
Incompatibility with Craftify

### ISSUE THREAD

**Issue by bjsho** [sleepingdragoninn/antique-atlas#187]
It's not really major to me, but maybe others, anyways ill add the log, just in case anyone wants to try and fix it, if its not a issue with antique-atlas, i can also do a bug report at craftify
[2024-08-07-6.log](https://github.com/user-attachments/files/16533241/2024-08-07-6.log)

**Comment by sleepingdragoninn** [comment]
atlas isn't present in the stack trace here, does the crash resolve if you remove atlas? 
![image](https://github.com/user-attachments/assets/798897dc-33fb-4cd2-a911-2faddcbd271c)

**Comment by bjsho** [comment]
Sorry for the late reply, yes it does

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/user-attachments/assets/13885377-98f7-46db-a9a6-fc3c4761eaa4)

can't reproduce on latest of both
