### ISSUE TITLE
joining server instantly disconnects with internal exception error

### ISSUE THREAD

**Issue by marigauge** [sleepingdragoninn/antique-atlas#188]
attached is the errors in latest log and server console upon joining, structure related maybe? the person in question was exploring the end, modified by BetterEnd and found themselves unable to rejoin. i teleported to their current position and looked around, opened the map, rejoined and was unable to reproduce, assuming they came across something along the way that caused issues; there's no crash, just a disconnect, excuse my potentially improper form
[latest.log](https://github.com/user-attachments/files/16540277/latest.log)
[console error](https://github.com/user-attachments/files/16540279/message.9.txt)

**Comment by marigauge** [comment]
fixed in latest version i was running 2.9.12 soooorrry i wish i could delete

**Comment by YOUNIN15** [comment]
> fixed in latest version i was running 2.9.12 soooorrry i wish i could delete

Something similar is happening to me, I have several mods and I get a lot of antique atlas errors from the client.

Today a friend of mine won't let him join the server anymore, it just crashes the game when he tries to join.
