### ISSUE TITLE
Missing structures and map resets

### ISSUE THREAD

**Issue by SireAwfulThe1st** [sleepingdragoninn/antique-atlas#19]
Nearly every kind of structures save than nether portals are missing, and it seems like randomly the map would reset and forgets all of it's previous constants in my playthroughs.

also would love tae have the atlas as a book item again for the immersion tho.

otherwise that's all I could report for now.

**Comment by sleepingdragoninn** [comment]
what version of the mod is the map clearing? which structures are missing?

**Comment by SireAwfulThe1st** [comment]
> what version of the mod is the map clearing? which structures are missing?

it's the latest one I always updates it towards the latest version, also it's like, nearly every structures, including modded that I assume is plainly because it's not supported yet or modified ones like CTOV, Yung's better structures series, etc

**Comment by sleepingdragoninn** [comment]
non-vanilla structures aren't in-scope for issues, and vanilla structures should be covered by existing issues - if there's a vanilla structure that isn't covered by issues, let us know.

If you experience your map disappearing again, please upload your `logs/latest.log` to https://mclo.gs/ and open a new issue with the link.
