### ISSUE TITLE
Crash when trying to join a server

### ISSUE THREAD

**Issue by YOUNIN15** [sleepingdragoninn/antique-atlas#191]
Today a friend of mine won't let him join the server anymore, it just crashes the game when he tries to join.

In his and my log there are also a lot of antique atlas errors.

Fabric 0.16.0, minecraft 1.20.1.

Antique Atlas 2.9.13

When he joins this appears in the server log
![image](https://github.com/user-attachments/assets/76e03836-5c96-462c-b346-abface12d4b6)

All these errors (many errors) appear in the client's log.
![image](https://github.com/user-attachments/assets/19fcb699-a6b6-455f-a98f-5e124904f4cf)

https://mclo.gs/m5af0MA

**Comment by sleepingdragoninn** [comment]
Those antique atlas errors are non-critical (we should probably de-escalate both types to better indicate this), I don't see anything atlas related at all around the crash. Does removing atlas fix the crash?

**Comment by YOUNIN15** [comment]
> Those antique atlas errors are non-critical (we should probably de-escalate both types to better indicate this), I don't see anything atlas related at all around the crash. Does removing atlas fix the crash?

You are absolutely right, it was not a problem with the atlas, but they should do something to try to avoid errors and make it compatible with modified biomes, I know it is possible with data packages, but it would be a great idea to develop them and publish them for end users, that would help the mod a lot.
