### ISSUE TITLE
Help with mod compatibility

### ISSUE THREAD

**Issue by DonVixote** [sleepingdragoninn/antique-atlas#192]
Hi, new to modding here, i was trying to play with these mods, but antique atlas map doesn't show up on crafting. Please help. Playing on fabric btw
![image](https://github.com/user-attachments/assets/a28fa533-b846-4720-bb5c-3e98cc5811e2)

**Comment by sleepingdragoninn** [comment]
I think you're confused about the feature set of AA4, we updated the [mod description](https://modrinth.com/mod/antique-atlas-4) for this recently.

(dupe of #133 #130 #90 #53)
