### ISSUE TITLE
Stay in delete mode by holding shift

### ISSUE THREAD

**Issue by Krimatoria** [sleepingdragoninn/antique-atlas#195]
To make the label removal button switchable, it is impossible to press again and again every time to remove the death mark.
![2024-08-18_12 19 37](https://github.com/user-attachments/assets/74f48bc2-fe65-4054-a797-33ae1178ef6f)

**Comment by sleepingdragoninn** [comment]
sure, we'll make it while holding shift, i think this used to be a feature but it got lost somewhere.

**Comment by Krimatoria** [comment]
> sure, we'll make it while holding shift, i think this used to be a feature but it got lost somewhere.

I also noticed a problem with the Waystones' Obelisk labels https://github.com/sisby-folk/antique-atlas/issues/200

**Comment by Krimatoria** [comment]
> sure, we'll make it while holding shift, i think this used to be a feature but it got lost somewhere.

Nice))))
