### ISSUE TITLE
Incompatibility with invalid structure references in a chunk

### ISSUE THREAD

**Issue by 3dEADto2** [sleepingdragoninn/antique-atlas#196]
Minecraft 1.20.1
Fabric 0.15.11
Antique Atlas 2.9.13

With the mod enabled the game crashes on world join.
[crash-2024-08-19_04.56.59-server.txt](https://github.com/user-attachments/files/16655306/crash-2024-08-19_04.56.59-server.txt)

**Comment by sleepingdragoninn** [comment]
one of your mods is breaking the order that chunks/structures are supposed to load, we'll add a safety check.

**Comment by sleepingdragoninn** [comment]
should be fixed with surveyor 0.6.22, just add that in manually

**Comment by 3dEADto2** [comment]
Thank you =)
