### ISSUE TITLE
Missing Biome: Cherry Grove

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/antique-atlas#2]
Tiles, texture sets, and textures need to be added for cherry groves (1.20+)

This is currently covered by the regular mountain texture, which isn't as clear.

**Comment by sisby-folk** [comment]
hey @kallmetony - did you make the cherry tree sprite for [kallmetony#6](https://github.com/kallmetony/AntiqueAtlasReborn/pull/6/files)? 

We're working on fleshing out the itemless fork for modrinth here - not sure how much yet - and we'd be happy to take it on as a contribution. Mangrove swamp is missing too if you were interested in modifying the existing swamp texture to be more unique.

**Comment by kallmetony** [comment]
can i have your discord to discuss it? my discord @ is the same as github, text me please

**Comment by sisby-folk** [comment]
added, you should have a request
