### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by KingLoserX** [sleepingdragoninn/antique-atlas#201]
The two errors include: Requires connector despite me having the correct connector downloaded and requires fabric_api 0.102.0+1.21 however the only available file of the FFAPI for Minecraft 1.21.0 is [1.21] Forgified Fabric API 0.101.2+1.21

[crash-2024-08-23_21.30.46-fml.txt](https://github.com/user-attachments/files/16733438/crash-2024-08-23_21.30.46-fml.txt)

**Comment by sleepingdragoninn** [comment]
fixed in 2.9.16
