### ISSUE TITLE
[FEATURE] Removing terrain will affect the map

### ISSUE THREAD

**Issue by makumaku1974** [sleepingdragoninn/antique-atlas#203]
idk how this would work but yeah rivers are so annoying if they aren't truly connected in vanilla minecraft. There are mods that does that job but I think doing a man made river should affect Antique Atlas.

Antique Atlas seems to be pretty dependent on biomes, structures, and other natural generations rather than players. The Player should have a function with the map itself and able to affect it, and not just simply adding waypoints, deathpoints, or markers.

**Comment by sleepingdragoninn** [comment]
digging bigass ravines does actually show up on the map - give it a try!

**Comment by sleepingdragoninn** [comment]
water should be as well if the body of water is big enough, if that's not happening that's a bug - try with worldedit just to be sure.

**Comment by makumaku1974** [comment]
> water should be as well if the body of water is big enough, if that's not happening that's a bug - try with worldedit just to be sure.

im using axiom. i'd try again testing this one out.

**Comment by makumaku1974** [comment]
I see it now. It works okay but needing to restart my world is just a bit tiresome. Is there not a method refresh that would affect in real time? Does F3 + A affects the refreshing of Atlas Map? This could have been a better way than re-logging into my world everytime.
