### ISSUE TITLE
Antique Atlas Doesn't seem to load properly Neo Forge 1.21

### ISSUE THREAD

**Issue by zukulent0** [sleepingdragoninn/antique-atlas#205]
I recently installed the 2.9.17+1.21 version of antique atlas, after opening a world and checking the map it doesnt load properly and it looks like its blurred/darked out and cant be interacted with.

I tested with all the mods i have and without them and the issue persist so its not a mod compatibility issue from the ones i added.

These are the mods i used to test and send the screenshot.

- antique-atlas-2.9.17+1.21
- connector-2.0.0-beta.1+1.21-full
- forgified-fabric-api-0.101.2+2.0.9+1.21

I tested on the fabric loader and it works, so I'm unsure what could be causing this.

![Atlas problem Neo Forge](https://github.com/user-attachments/assets/e0b2b015-e1be-4069-8723-771dcef61e54)

**Comment by sleepingdragoninn** [comment]
fixed in a later connector version, might need to bump to 1.21.1 to use it.
