### ISSUE TITLE
Poor scaling

### ISSUE THREAD

**Issue by ch4nchito** [sleepingdragoninn/antique-atlas#206]
Bad scaling for 4:3 displays, I suggest either just putting a wide interface or fixing the scaling...
![javaw_eo0YIj0794](https://github.com/user-attachments/assets/f6938250-8876-4a72-8fef-db51307497dc)

**Comment by sleepingdragoninn** [comment]
hm, that's kind of the nature of the stitching being done on the background - does setting fullscreen to false help?

**Comment by ch4nchito** [comment]
> hm, that's kind of the nature of the stitching being done on the background - does setting fullscreen to false help?

no, it's just about the aspect ratio of the window itself
![0frepa1SDJ](https://github.com/user-attachments/assets/19975ac5-a448-42ff-9ec7-b81e2d50a5a4)
![p2aISvPitC](https://github.com/user-attachments/assets/d7f500e5-cccb-4d59-9aee-ff861748cbd0)

**Comment by sleepingdragoninn** [comment]
ah, I should clarify, the option called `fullscreen` in the config toml file

**Comment by ch4nchito** [comment]
oh ye, it fixed it, thanks

**Comment by ch4nchito** [comment]
in antique-atlas.toml
fullscreen = false
