### ISSUE TITLE
Crash with UnionLib

### ISSUE THREAD

**Issue by BLUEChester** [sleepingdragoninn/antique-atlas#211]
Haven't been able to try the mod out yet as it keeps crashing whenever I try to open the map, I have heaps of mods so it might be incompatible with one, not sure which one though.

Heres all the logs:

[redacted] 

I had a brief read of the logs and it may be incompatible with UnionLib? I'm using the Violent Villagers mod with requires Unionlib

**Comment by sleepingdragoninn** [comment]
raw logs can contain personal information, so I've used mclo.gs https://mclo.gs/oVLfDTz

**Comment by sleepingdragoninn** [comment]
Yeah something in your modpack is completely bricking the ability for fabric reloaders to work in order - definitely bisect and report to the mod, that's pretty bad.

**Comment by BLUEChester** [comment]
Yes I figured it out it was Violent Villagers and/or its dependency UnionLib, so I might report it to that developer

**Comment by sleepingdragoninn** [comment]
sounds good!
