### ISSUE TITLE
Loading Previously Generated Chunks

### ISSUE THREAD

**Issue by codemaster101-web** [sleepingdragoninn/antique-atlas#212]
It'd be nice if this mod could load previously loaded chunks like Xaero's World Map. I tried using the player-sharing feature tool to transfer the Xaero's data to Antique Atlas 4, but you can't share maps between yourself. Thanks!

**Comment by sleepingdragoninn** [comment]
shuffle this one to sisby-folk/surveyor - a batch-world-processing button would be interesting.
