### ISSUE TITLE
Map information resets randomly.

### ISSUE THREAD

**Issue by Komotomoth** [sleepingdragoninn/antique-atlas#214]
Occasionally while playing with the mod, the map would reset (but the waypoints would stay). In the screenshot it shows waypoints I had in previously mapped areas. I don't know what causes the issue or how to fix it.
![Screenshot 2024-09-08 205934](https://github.com/user-attachments/assets/e734fdcd-1c00-4394-9a1a-9f7e16be90e0)

**Comment by sleepingdragoninn** [comment]
please add your screenshot / logs (mclo.gs) to #170
