### ISSUE TITLE
Atlas shows landmarks only incompatibility

### ISSUE THREAD

**Issue by TheRealMrSnowman** [sleepingdragoninn/antique-atlas#215]
Using the mod in both single player and multiplayer the map is completely blank.
Surveyor is installed on both the server and the client.
The map can see landmarks but nothing else.

![image](https://github.com/user-attachments/assets/77ad786d-72da-4d0b-a2c6-586afe40eade)
![image](https://github.com/user-attachments/assets/c986263c-5aec-42a7-92c1-6f8e0396222e)

Game version: 1.20.1
Loader Version: 0.16.5

lemme know if you want a log file

**Comment by sleepingdragoninn** [comment]
please post a log to mclo.gs - seems like another mod is breaking atlas.

**Comment by TheRealMrSnowman** [comment]
https://mclo.gs/cTJ5yfl

**Comment by sleepingdragoninn** [comment]
textures look fine, which means that another mod is extremely messing with the way that chunks load and work

**Comment by sleepingdragoninn** [comment]
closing this one as stale (3 months)
