### ISSUE TITLE
Dark and dim broken map on connector 1.21

### ISSUE THREAD

**Issue by TDEnderP** [sleepingdragoninn/antique-atlas#217]
![2024-09-12_19 49 20](https://github.com/user-attachments/assets/d1b16dc7-6dc3-4ca0-a225-207c8d58cbf8)
this is what opening the map looks like on a fresh new world, running on 1.21 latest version of neoforge with Sinytra Connector, the Fabric Forge API, and Surveyor Map Framework (tested without surveyor and same issue persists). What else would be helpful to provide? Sorry if this is an issue I should take up with connector I just thought to post this here since it is listed as a dependency to play on neoforge, so I assume you're trying to make it compatible

**Comment by sleepingdragoninn** [comment]
yeah this bug exists on an old version of connector, you need to update, probably to 1.21.1
