### ISSUE TITLE
Crashes on minecraft 1.20.4

### ISSUE THREAD

**Issue by NovelPhacelia** [sleepingdragoninn/antique-atlas#22]
Running on mc 1.20.4 and Fabric 0.15.6, mods are antique atlas 4 and FabicAPI, the game crashes when joining or creating world.
Seems similar to #12 

[latest.log](https://github.com/sisby-folk/antique-atlas/files/14189630/latest.log)
[crash-2024-02-06_21.58.00-server.txt](https://github.com/sisby-folk/antique-atlas/files/14189633/crash-2024-02-06_21.58.00-server.txt)

**Comment by sleepingdragoninn** [comment]
mod is not compatible with experimental hotfixes (1.19.3-4, 1.20.2-5)
