### ISSUE TITLE
Automatic markers for structures are not working. 1.20.1

### ISSUE THREAD

**Issue by ajmod73** [sleepingdragoninn/antique-atlas#221]
I'm running a modpack with this mod, I also have Surveyor installed, however, it does not automatically load in any structure icons when I visit them in-game. I'm using the 2.9.17 build for 1.20.1 with Prism Launcher. I have tried reinstalling it, making a new world, importing the .jar into the folder directly instead of using Prism, but nothing has changed. 

There is one caveat though, I noticed whenever I load into the game it gives me this massive error text wall in the console which relates to the map atlas.

[Render thread/ERROR]: [Antique Atlas] Error reading structure tile provider minecraft:start/village_taiga!
java.lang.IllegalStateException: Marker texture antique_atlas:structure/taiga_village does not exist!

It looks like this is true for every structure in the mod.
here's the full error message related to atlas (it is 17,000+ lines long lol):
[atlas_error.txt](https://github.com/user-attachments/files/17021906/atlas_error.txt)

I really love this mod but this has been frustrating me a bit ehe, is there anything I can do or am I just screwed =^= thanks =3

**Comment by sleepingdragoninn** [comment]
You've got a mod completely breaking fabric reloader ordering - you'll have to figure out which one.

**Comment by Adirelle** [comment]
Hello,

I have the same issue. Is there are way to detect such mod?

**Comment by sleepingdragoninn** [comment]
This is a generic issue with a mod, or a mod/connector issue - any other mod that relies on fabric reloader dependencies would also break. bisecting is the only solution. Going to close this as stale.
