### ISSUE TITLE
Fallbacks don't work for datapack biomes (Terralith)

### ISSUE THREAD

**Issue by catter1** [sleepingdragoninn/antique-atlas#223]
First of all, yes, I have read #83! This is exactly why I am making this issue.

## Issue
Recently, a couple people have mentioned that Antique Atlas is not recognizing any fallback biome for many of Terralith's biomes. According to the log (linked at bottom of issue), the cause of this is due to the Terralith biome not being listed in any conventional or vanilla tag. This is confirmed and explained further in the aforementioned #83.

However, all of Terralith's biomes *are* in conventional and vanilla tags. For example, let's take `terralith:desert_spires`.
1. In [line 132](https://mclo.gs/GBVN2jF#L132) of the log, Antique Atlas cannot find Desert Spires in any conventional or vanilla tag
2. [Your code](https://github.com/sisby-folk/antique-atlas/blob/1.21/src/main/java/folk/sisby/antique_atlas/reloader/BiomeTileProviders.java#L124-L125) checks for `c:is_desert`, `c:is_wasteland`, and `c:is_dead`; as well as the corresponding Forge tags (which are irrelevant here)
3. Look inside the latest version of Terralith, open up `c:is_desert`, and see that `terralith:desert_spires` is inside of it
    - Yes, it's a little bit of a maze, with a couple of linked tags
    - Terralith's GitHub is not updated to the latest version (2.5.5), and I do apologise for that - looking through the mod itself is required

![image](https://github.com/user-attachments/assets/e4126bae-7a2c-4584-9df2-7bd542b131af)
![image](https://github.com/user-attachments/assets/fe3abf40-b7f7-4275-9a84-1679922b1d78)
![image](https://github.com/user-attachments/assets/7e10d158-79fb-4e37-b208-88cfec36e207)

## Note
I did leave out one detail. The warning in the log states "not in ANY [...] tag **on the client**". Terralith is a datapack pretending to be a mod. As a datapack developer, I know that the tags are typically only loaded onto the server. In this scenario however, the Terralith mod is installed onto the client. The alternative being a player joining a server with Terralith installed, when they do not have it installed.

Another reason this potential cause does not make sense, is because Antique Atlas *does* find a backup biome for some of Terralith's biomes. This implies it finds those biomes inside of a tag somewhere, meaning at least some tags are loaded and recognized.

I also looked at the biomes Antique Atlas did find a fallback biome (aka a conventional/vanilla tag) for and compared them to the ones it did not find. Yet I could not spot any meaningful differences.

## Conclusion
Not sure why this is an issue. From glancing at your code, analyzing Terralith's biome tags, and reading your explanation on how Antique Atlas assigns fallback biomes, this should theoretically not be an issue. I do not know what could cause it. Perhaps I misunderstood something?

Let me know if there's an issue on Terralith's side, and I'll do my best to fix it. I should also note that a couple of texturers were thinking about making custom tiles for Antique Atlas to merge into Terralith's [optional resourcepack](https://modrinth.com/resourcepack/sparkles), but unsure if/when this will ever come to fruition.  

## Environment
- Minecraft: 1.21
- Terralith: 2.5.5
- Antique Atlas: 2.9.17
- Log: https://mclo.gs/GBVN2jF

**Comment by sleepingdragoninn** [comment]
could be a sync or timing issue due to being a datapack and not a mod, we'll investigate.

**Comment by lupowo** [comment]
Imo AA doesn't really work with terralith anyway. The automatic hight recognition might work in vanilla but terralith terain starts so high up that you basically only see the hilly and the highest versions of the tiles anyway on the atlas. Sea level is ~60 and most terrain thats not a beach starts at around 80 whitch, for plains for example, makes it basically never display the lower variant.

**Comment by sleepingdragoninn** [comment]
data-configurable sea level / elevation ranges is a good idea - covered by #77

**Comment by sleepingdragoninn** [comment]
So this definitely works in fabric singleplayer, so i'm going to explicitly test the "vanilla server with a datapack" case

![image](https://github.com/user-attachments/assets/98c94e53-38e9-4c21-9318-03d054091f94)

**Comment by sleepingdragoninn** [comment]
looking good! I think this is fixed in latest. Let me know if not.

![image](https://github.com/user-attachments/assets/1435278c-fa8b-4c17-ab22-8886148a983b)

**Comment by nitodeco** [comment]
Damn I've had this issue for a while and just yesterday made my own resource pack to fix it...Wish I would have seen this issue beforehand
