### ISSUE TITLE
Question/suggestion: any way for this mod to include player built stuff?

### ISSUE THREAD

**Issue by SpaceNerd95251** [sleepingdragoninn/antique-atlas#224]
As far as I can tell, the mod will show you the terrain and stuff that normally generates. However, if, for example, you destroy a tree, that will not be reflected in the atlas, and the atlas will still claim there is a tree there, because that is where a tree naturally generated. This question also applies to buildings and stuff you make. Is this outside the scope of the mod, or considered intentional (with the philosophy you mentioned of the best way of looking at the world should be by being there) or is it just something that is difficult to implement that you might not want to do. No judgement either way of course, just a question

**Comment by sleepingdragoninn** [comment]
Player built stuff does affect the display of the map, but only when the player built stuff is large enough - a manually carved ravine will appear (substantial change in surface elevation), but clearing a forest will not (underlying biome does not change).

Like the description mentions, atlas tries to avoid making player bases visible on the map in a way that differs from vanilla or standard map mods - I'd recommend using map markers instead.

So yes, this is mostly outside of scope. Marking what a player has done is primarily down to the player and their own use of markers.

For april fools next year we were considering making "pedantic atlas", where players manually place each tile on the map - so keep an eye out for that ahahah

**Comment by SpaceNerd95251** [comment]
Got it, thanks
