### ISSUE TITLE
Lags with shaders enabled

### ISSUE THREAD

**Issue by Krimatoria** [sleepingdragoninn/antique-atlas#23]
At the same time, it is a flat world. Very strong FPS drawdowns critical TPS drops when using Shaders up to several thousand points. Different amount of FPS drawdown when zooming in or out of the map.

![2024-02-16_00 49 33](https://github.com/sisby-folk/antique-atlas/assets/106809386/a557e686-be8a-4df8-8317-c68f6428f63d)

<details>
<summary> Image </summary>

![image](https://github.com/sisby-folk/antique-atlas/assets/106809386/9a76a172-588c-48bf-ad04-b9ef9d3ec818)
Not drawing villages. Strange objects on the map. There's nothing here. The vanilla village is not drawn.
![2024-02-16_00 51 05](https://github.com/sisby-folk/antique-atlas/assets/106809386/3bfa857c-1387-49d7-b50d-e1d875243a26)
![2024-02-16_00 45 43](https://github.com/sisby-folk/antique-atlas/assets/106809386/ef33ab87-cf6c-4791-ba85-11174fa8ebef)
![2024-02-16_00 46 10](https://github.com/sisby-folk/antique-atlas/assets/106809386/8752e866-abbd-4eba-b90c-40b7275c5ec2)
![2024-02-16_00 46 26](https://github.com/sisby-folk/antique-atlas/assets/106809386/8e6123d6-7df9-45e0-b1aa-e2e86c75a868)
![2024-02-16_00 46 29](https://github.com/sisby-folk/antique-atlas/assets/106809386/74c65a54-6210-4d08-8f95-ddf92f701417)
![2024-02-16_00 46 52](https://github.com/sisby-folk/antique-atlas/assets/106809386/3e7aa2c4-65c5-424b-8a9f-a3ac746189f1)
![2024-02-16_00 46 54](https://github.com/sisby-folk/antique-atlas/assets/106809386/17c0962e-2d12-4bb1-ad7a-e3f2e4a285a5)
![2024-02-16_00 46 57](https://github.com/sisby-folk/antique-atlas/assets/106809386/580052bb-c13d-4be1-a667-06573741702a)
![2024-02-16_00 48 29](https://github.com/sisby-folk/antique-atlas/assets/106809386/bd982a2f-c45a-4e30-95f2-b52ee999abf1)
![2024-02-16_00 48 33](https://github.com/sisby-folk/antique-atlas/assets/106809386/fdcf724d-6598-45fb-8f45-1b36523e55d1)
![2024-02-16_00 49 25](https://github.com/sisby-folk/antique-atlas/assets/106809386/cc7e26b9-4721-4f98-b93f-63bb6ae0230e)
![2024-02-16_00 50 09](https://github.com/sisby-folk/antique-atlas/assets/106809386/6dc11ace-4710-4212-8dcb-c008f323bd49)
</details>

**Comment by sleepingdragoninn** [comment]
Can you clarify what shader mod you are using here? Optifine? Oculus?

**Comment by Krimatoria** [comment]
> Reference in ne

oculus-mc1.19.2-1.6.9.jar
Insanity-Shader-Universal-v1.500.zip

**Comment by sleepingdragoninn** [comment]
Closing this now that we've majorly reduced the amount of draw calls made for tiles on the map in 2.2 - open a new issue if it reoccurs >=2.2
