### ISSUE TITLE
Lockable Zoom?

### ISSUE THREAD

**Issue by LloydValkyria** [sleepingdragoninn/antique-atlas#231]
It's not really an issue but more of a request. Could there be an addition to where we can lock a specified scale zoom so that even if we want to enlarge the map, the textures won't shrink down into their zoomed-out form? Not sure if that makes sense. Just so we can zoom out at the selected scale of the map versus it compressing. Or heck just a lock on the zooming in general for fun?

**Comment by sleepingdragoninn** [comment]
Have you played around with the map scale settings in antique_atlas.toml? that should almost certainly cover what you're looking for I'd think

**Comment by LloydValkyria** [comment]
Oh wait it's a thing?!

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/user-attachments/assets/d2f321cd-86d9-4510-a3a6-3350ad7c5f3c)

I think these 3 settings should cover you?
