### ISSUE TITLE
Paper support?

### ISSUE THREAD

**Issue by Regianus** [sleepingdragoninn/antique-atlas#237]
Is there any way AA could be ran in paper servers?

**Comment by sleepingdragoninn** [comment]
theoretically it would be possible to implement surveyor on paper from what i understand of the compatible plugin systems - in practice? it's way too heavy to not be an absolute nightmare - I wouldn't pursue it, and I wouldn't support the work of anyone who tried.

Just live without structure discovery / map sharing or swap to a fabric server with optimization mods - both decent options.
