### ISSUE TITLE
[Feature Request] Waypoint Guide

### ISSUE THREAD

**Issue by alexmozaidze** [sleepingdragoninn/antique-atlas#239]
Xaero's minimap can show all the waypoints directly in the world, it would be useful to have something of a similar kind for Atlas.

A compass maybe? Something that can be themed to not feel alien to the main mod.

**Comment by sleepingdragoninn** [comment]
because antique atlas waypoints use surveyor as storage, this can be done as a surveyor addon rather than an antique atlas feature.
