### ISSUE TITLE
Fallback biomes don't work in multiplayer

### ISSUE THREAD

**Issue by Mangraz** [sleepingdragoninn/antique-atlas#24]
In multiplayer, the modded biome from Traverse "Autumnal Forest", shows up on the map as a colorful mess. The bug only occurs in multiplayer. Playing the same save file in singleplayer, the map works fine and shows a forest. Using version 1.1.4.
![2024-02-20_19 17 26](https://github.com/sisby-folk/antique-atlas/assets/95761308/90184491-b4d1-4a05-815e-2db6a267e875)

**Comment by sleepingdragoninn** [comment]
biome tags aren't sent serialized to the client correctly - either traverse is doing something wrong or your loader.

**Comment by Mangraz** [comment]
I see, I'll report to the Traverse team then. Thanks for your reply!

**Comment by sleepingdragoninn** [comment]
@Mangraz can you check this out on 1.4.2? We've made several improvements to fallbacks and it really should only happen if biome tag sync is completely broken now.

**Comment by Mangraz** [comment]
Still broken unfortunately. Updated client and server.

**Comment by sleepingdragoninn** [comment]
Can you confirm whether this happens with only traverse, antique atlas, and dependencies? Either way, send a logs/latest.log uploaded to http://mclo.gs/

**Comment by Mangraz** [comment]
[Here's the log.](https://mclo.gs/Hcrk0eZ) On a sidenote, Nature's Compass seems to be reading biome tags correctly. Shows e. g. Autumnal Forest with a Forest tag etc. Also noticed in the log that Antique Atlas has the same error with BetterNether and BetterEnd, checked ingame and yep, there's the colorful mess again. 

Tried clean install of client and server with only Traverse and Antique Atlas, same issue. [Client log](https://mclo.gs/gzc6RRk) [Server log](https://mclo.gs/1goBkKj). Hope this helps!

**Comment by sleepingdragoninn** [comment]
Thanks for that! Definitely seems like biome tags aren't being synchronised - I guess it's possible that vanilla doesn't send biome tags at all? we'll look into it and either ship a workaround if it's a vanilla issue, or report it to traverse if they missed something.

It's also possible that we're running this code too early for tags if they're really sent per-world - that'd be on us - we'll check it out!

**Comment by sleepingdragoninn** [comment]
Replicated - every biome mod has this issue, so it seems like it's either on our end or vanilla's end, we'll take a look today.

**Comment by sleepingdragoninn** [comment]
good news! looks like its a timing issue on the antique atlas end - we should be able to move our fallback registration later and fix this issue.
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/7bd721ac-a6b9-4bcd-bfde-a1294364c628)

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/97b0f7ee-e3ac-421e-a2d2-cb73263733a0)

fixed in 1.4.3!

**Comment by aziles-guts** [comment]
This appears to still be an issue with biomes o' plenty on 1.4.3

**Comment by sleepingdragoninn** [comment]
post a log!
