### ISSUE TITLE
help with making respack

### ISSUE THREAD

**Issue by JohnWeak1** [sleepingdragoninn/antique-atlas#244]
I read the wiki to try and add compatibility for modded biomes (terrafirmacraft) and there are still question marks, is there something I don't understand ?

`assets/tfc/atlas/biome/plains.json` :
```json
{
  "textures": {
    "valley": [
      "atlas_compat:base/grass",
      "atlas_compat:biome/flatland/plains/grass_3",
      "atlas_compat:biome/flatland/plains/grass_oak_sparse",
      "atlas_compat:biome/flatland/plains/grass_oak_fancy_tall_sparse",
      "atlas_compat:biome/flatland/plains/grass_oak_fancy_sparse"
    ],
    "high": {
      "atlas_compat:biome/flatland/plains/grass_hills_low": 4,
      "atlas_compat:biome/flatland/plains/grass_oak_sparse_hills_low": 1,
      "atlas_compat:biome/flatland/plains/grass_oak_fancy_tall_sparse_hills_low": 1,
      "atlas_compat:biome/flatland/plains/grass_oak_fancy_sparse_hills_low": 1
    },
    "peak": "atlas_compat:biome/flatland/plains/grass_hills"
  }
}
```

`assets\atlas_compat\textures\atlas\tile\biome\flatland\plains` folder (taken from the base mod textures) :
![image](https://github.com/user-attachments/assets/da0e41b9-729e-4ab1-8c08-5e4ac4a421ec)

I would like it for someone to tell me what I did wrong, thank you

**Comment by JohnsonJohnsonson** [comment]
Exactly the same issue here:
Resource Pack is active and (as far as I can tell) correctly configured:
```
// assets/aether_redux/atlas/biome/cloudcaps
{
  "textures": 
    {
      "antique_atlas:biome/nonland/mushroom/mycelium_mushrooms_huge_mixed_dense",
      "antique_atlas:biome/nonland/mushroom/mycelium_mushrooms_huge_red_edge"
    }
}
```
but ingame, it just shows question marks with "missing" as the debug text
![image](https://github.com/user-attachments/assets/3cd1d8fb-7da2-40f4-8aec-702e30af4249)
![image](https://github.com/user-attachments/assets/6259d25b-9a02-4101-af21-1c494595d240)

**Comment by sleepingdragoninn** [comment]
pretty sure these are two unrelated issues - OP you need to enable debug mode and screenshot an instance of the biome you've made a respack for in-game and show what it looks like. 
Reply, it looks like your respack file is invalid - your logs/latest.log will be giving you an error telling you this, but lists of textures need to be enclosed in [], not {}

**Comment by JohnsonJohnsonson** [comment]
apologies, I'll make my own issue

**Comment by sleepingdragoninn** [comment]
@JohnWeak1 could you set `debugRender = true` in `config/antique_atlas.toml` and then show what a terrafirmacraft plains biome looks like in-game? Hover the mouse over that part of the atlas so the debug output is visible.

**Comment by MattIwicki** [comment]
Same problem here so I'm continuing the thread.

![image](https://github.com/user-attachments/assets/3d5f2db4-f585-41ec-b4a1-94cd4360bea4)

![image](https://github.com/user-attachments/assets/31c3caa9-9ae8-44af-abef-3ae6f5c1a038)

![image](https://github.com/user-attachments/assets/e8973c90-f00e-4915-830c-82731f46709f)

**Comment by lupowo** [comment]
@MattIwicki i think your problem is that you have not provided any textures, just the base ones and i dont think those are enough.

could also be that the plains biome is a vanilla biome as well as a tfc one. maby AA or surveyor gets confused here. Is the texture in the base folder? you could also provide a log. Most of my problems with missing textures have been solved by takeing a look at that.

**Comment by sleepingdragoninn** [comment]
If all you're trying to do with a respack is make biomes use standard tiles instead of being ???s, it's far more productive to just add missing biome tags. No need to make an atlas pack.

**Comment by sleepingdragoninn** [comment]
closing this one for being too piecemeal

**Comment by Wackywee** [comment]
Hi, I'm reopening this because the recommended fix of putting brackets around the biomes meta data folder didn't work

**Comment by Wackywee** [comment]
[
    {
    "textures": {
      "valley": [
        "antique_atlas:biome/woodland/forest/oak_fancy_mixed",
        "antique_atlas:biome/woodland/forest/oak_mixed",
        "antique_atlas:biome/woodland/forest/grass_oak_mixed"
      ],
      "high": [
        "antique_atlas:biome/woodland/forest/oak_fancy_mixed_hills_low",
        "antique_atlas:biome/woodland/forest/oak_mixed_hills_low",
        "antique_atlas:biome/woodland/forest/grass_oak_mixed_hills_low"
      ]
    }
  }
]
