### ISSUE TITLE
Atlas Map Data Not Synching until relog on server

### ISSUE THREAD

**Issue by Purple-Towel** [sleepingdragoninn/antique-atlas#247]
Using antique_atlas 2.10, sinytra connector 1.0.0 beta 46, fabric api 0.92.2+1.11.8 and surveyor 0.6.24 it appears that either surveyor/antique atlas isn't properly synching data on my server until a client player relogs.

I am hosting the server on my own machine and I've ensured that both my friends and I are using the same versions of the 4 mods and all of us experience this desynched Atlas data until we log out and back in again, which will update the data and then get desynched again.

I can provide further details as necessary.

**Comment by sleepingdragoninn** [comment]
will close this one preferring the farsight issue
