### ISSUE TITLE
No biomestextures.json as in previous versions

### ISSUE THREAD

**Issue by gcook725** [sleepingdragoninn/antique-atlas#25]
I'm unsure if this is a planned feature at some point, but previous versions of Antique Atlas had the option to manually add and edit textures on a per biome basis. This allowed for custom textures as well as compatibility with mods that added new biomes.

**Comment by sleepingdragoninn** [comment]
this has been handled though resource packs for quite a few versions now I think! feel free to check the wiki on the previous repo or browse the resources folder on this repo manually for examples.

When 2.0 is done, we'll likely republish new docs.
