### ISSUE TITLE
Game crashes when entering spawn chunks or respawning.

### ISSUE THREAD

**Issue by przyg** [sleepingdragoninn/antique-atlas#250]
When using the newest version of Antique atlas 4 for forge 1.20.1 game crashes when entering spawn chunks or respawning, disabling the mod stops this, it also crashes when using planes from simple planes mod. Everything works normally when i disable the Antique Atlas mod

**Comment by sleepingdragoninn** [comment]
insufficient info, logs/latest.log to https://mclo.gs/, given the context likely a palette bug, so I'd need your world/data/surveyor folder as well. Will reopen if provided.
