### ISSUE TITLE
add config option to not show player indicator

### ISSUE THREAD

**Issue by SivyxDev** [sleepingdragoninn/antique-atlas#251]
adding a config option to disable the player indicator would allow the map to act as a visual supplement rather than as a functional minimap. this would be helpful for cases where players don't want to use a minimap which shows their exact location and want to navigate via the world instead.

**Comment by sleepingdragoninn** [comment]
duplicate of #168

**Comment by SivyxDev** [comment]
understood. I have created a modified version of the mod which roughly implements this for my use. Am I allowed to make this publically available in a modpack? thank you

**Comment by sleepingdragoninn** [comment]
LGPLv3! go nuts
