### ISSUE TITLE
Antique Atlas 4 + Big Globe

### ISSUE THREAD

**Issue by Rubinchik11095** [sleepingdragoninn/antique-atlas#256]
Hello, I noticed that the Antique Atlas 4 mod is not compatible with the Big Globe mod, I found vesual bugs on the mine map.
Can you please add compatibility of your mod with Big Globe

**Comment by sleepingdragoninn** [comment]
duplicate of #83

**Comment by Rubinchik11095** [comment]
Thanks for the answer, but I don’t remember anything (
