### ISSUE TITLE
Biome Compatibility: Biomes O' Plenty

### ISSUE THREAD

**Issue by Malberee** [sleepingdragoninn/antique-atlas#30]
How can I use Antique Atlas in conjunction with Biomes O' Plenty?
![2024-02-27_18 04 19](https://github.com/sisby-folk/antique-atlas/assets/82259650/7df881f5-cf55-4b24-bc6b-e08083e20a06)

**Comment by sleepingdragoninn** [comment]
I believe Golrith's coloured texture pack for antique atlas on 1.12 supported Biomes O' Plenty, but its format is massively outdated now even for 0.x - it may be able to be converted as the textures themselves are in the right format, just not the json.

[link](https://drive.google.com/file/d/1ta8B_-rzQ9opKIq2olDPX5HWJ5Ct-FHJ/view?usp=sharing) to the old pack for anyone who's looking to take that up - though I'd recommend waiting for 2.0 to release as we're planning on simplifying the respack format even more.

**Comment by Malberee** [comment]
Thanks for the reply. For those who will face the same problem: On the Antique Atlas Discord server I found a link to a resource pack that has a new format and seems to be compatible with new versions, but apparently it is not finalized, so not all biomes from Biomes O`Plenty work correctly, so it can be finalized a bit and used.
https://github.com/AntiqueAtlasTeam/AntiqueAtlas/releases/download/6.0.1-forge/Golrith.zip
