### ISSUE TITLE
Vanilla Biome: Dripstone Caves

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/antique-atlas#31]
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/00709c74-192d-477f-9900-576202e64275)

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/5a0602d1-34b7-4a93-a3fa-50443cdbf1a6)

**Comment by sleepingdragoninn** [comment]
Assigned the ravine texture as a fallback for this. "ravine with spikes" is probably the goal.

**Comment by lumiscosity** [comment]
added in [1a09fa8](https://github.com/sisby-folk/antique-atlas/commit/1a09fa80bfa1c86ede9019907e25294818b6188f), can be closed
