### ISSUE TITLE
Vanilla Biome: Lush Caves

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/antique-atlas#32]
Like dripstone, it's possible (if unlikely) for lush caves to be exposed.

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/09d0c8aa-6758-4cf2-8f12-88919888b1e9)

**Comment by lumiscosity** [comment]
added in [1a09fa8](https://github.com/sisby-folk/antique-atlas/commit/1a09fa80bfa1c86ede9019907e25294818b6188f), can be closed
