### ISSUE TITLE
Missing Structure: Trail Ruins

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/antique-atlas#4]

**Comment by lumiscosity** [comment]
trail ruins don't have much in the way of above-ground appearance, so they're tough to make a readable tile or marker for; perhaps a brush marker could be implemented instead?

**Comment by sleepingdragoninn** [comment]
happy with the brush marker for this one and think the issue is visible enough while closed. We might reassess in future but I think this one can be unmarked.
