### ISSUE TITLE
Blueprint bricks reloaders on Connector

### ISSUE THREAD

**Issue by Barerock** [sleepingdragoninn/antique-atlas#42]
Crash log: 
[crash-2024-03-06_18.53.05-client.txt](https://github.com/sisby-folk/antique-atlas/files/14516906/crash-2024-03-06_18.53.05-client.txt)

Too tired to parse out any details for sure. Game is fine without opening the map.

**Comment by sleepingdragoninn** [comment]
Can't immediately see what kind of issue this is - can you upload your logs/latest.log to https://mclo.gs/ and post a link?

**Comment by Barerock** [comment]
Crash Log: https://mclo.gs/ihgQxys
Latest Log: https://mclo.gs/XDnbV8m

**Comment by Barerock** [comment]
Latest log includes many errors for disabled mods that aren't doing anything, like Valkyrien Skies.

**Comment by sleepingdragoninn** [comment]
I can see you're running connector - can you check if this issue occurs in an instance with just forge, connector, ffapi, and antique atlas?

**Comment by Barerock** [comment]
Sure thing

**Comment by Barerock** [comment]
Working on another thing, might take a second :)

**Comment by Barerock** [comment]
It does not crash, meaning it's time to do yet another breakdown of my mod list ffs.

**Comment by Barerock** [comment]
Unless you can spot anything that you know is incompatible, that'd be super duper helpful.

**Comment by sleepingdragoninn** [comment]
The crash is related to either identifier construction being utterly broken, or default valued registries being utterly broken - these are both very core functionalities so whichever mod is doing it, i'd steer very clear of it.

**Comment by Barerock** [comment]
Great to know, that's usually what I do when something else is a culprit for crashes. Hopefully it's not something I really like. Thanks :D

**Comment by Barerock** [comment]
I'll note that mod here when I'm done in however long that is. Probably not until this weekend.

**Comment by Barerock** [comment]
I can't even get this mod to load sometimes, making testing extremely hard.

**Comment by Barerock** [comment]
What's this about?
![image](https://github.com/sisby-folk/antique-atlas/assets/38869993/6a951774-a3b4-43ed-8440-03d44c2b3364)

**Comment by Barerock** [comment]
no message in log.

**Comment by Barerock** [comment]
Oh it's probably super incompatible with Terralith? That's all I can think of. Anyway, the incompatible mod is Blueprint, a library.

**Comment by sleepingdragoninn** [comment]
Yep, in antique atlas, biome support is explicit unless the mod makes extensive use of vanilla tags - terralith doesn't remotely look like vanilla terrain most of the time, so it makes sense that it doesn't. 

We'll be further documenting respack formats and giving more fallback options in the config in 2.0

**Comment by Barerock** [comment]
Cool. Now I'm solving a much more annoying and almost game breaking bug with the SKY. Glad you're bringing AA back to life.

**Comment by sleepingdragoninn** [comment]
Hey hi there! Can you check if this crash is fixed on 2.2? If not, could you post fresh logs?

**Comment by Barerock** [comment]
Shore thang, never fixed that sky bug. I just clear weather when it happens.

**Comment by Barerock** [comment]
Seems to work with just a few mods + blueprint installed. The ? map is a lot more bearable to look at too lol, even if it is just as useless. Can't wait for modded biome support packs to release. Great work!

**Comment by Barerock** [comment]
[latest.log](https://github.com/sisby-folk/antique-atlas/files/14859743/latest.log)
Latest.log so you can see under the hood.

**Comment by sleepingdragoninn** [comment]
on inspection, your tile reload is completely broken - which would definitely explain having a useless map

**Comment by sleepingdragoninn** [comment]
https://mclo.gs/EW9wSO1 without blueprint: 
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/52c15c43-cf21-49f8-9050-ee64dc19c837)

https://mclo.gs/lNWxqPs with blueprint: ![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/2e6bb5df-01ce-4724-9b25-f6ae71c98439)

**Comment by Barerock** [comment]
Interesting lol

**Comment by sleepingdragoninn** [comment]
Issue is here - https://github.com/Sinytra/Connector/issues/919 - can you try downgrading to blueprint 7.0.0?

**Comment by Barerock** [comment]
Sure, in a min.

**Comment by sleepingdragoninn** [comment]
Yeah okay, on inspection blueprint 7.0.0 works fine, but blueprint mods on 1.20 need latest blueprint to function - overriding the version doesn't help either.

We'll just have to wait for connector or blueprint to fix this.

**Comment by Barerock** [comment]
Insert emoji_dissolving.gif

**Comment by sleepingdragoninn** [comment]
fixed in latest ffapi! we've come this far, want to check for remaining issues manually?

**Comment by Barerock** [comment]
Sure thing, prolly in a few hours though.

**Comment by Barerock** [comment]
Same result on the map, here's my latest.log
[latest.log](https://github.com/sisby-folk/antique-atlas/files/14891359/latest.log)

**Comment by sleepingdragoninn** [comment]
You've gotta update to [latest ffapi!](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.5+1.20.1)

**Comment by Barerock** [comment]
MMM I thought I did, oops

**Comment by Barerock** [comment]
It isn't listed in curse yet? Manual will do.

**Comment by Barerock** [comment]
IT

**Comment by Barerock** [comment]
WORKS

**Comment by sleepingdragoninn** [comment]
Thanks for the help! Looks like we helped out Sinytra a bit too. Cheers!
