### ISSUE TITLE
Port to Experimental Hotfixes / Milestone Snapshots (1.19.3+, 1.20.2+)

### ISSUE THREAD

**Issue by viktordimov** [sleepingdragoninn/antique-atlas#52]

**Comment by sleepingdragoninn** [comment]
Right now we're just on maintenance for everything until we finish and release 2.0 - at that point, 1.20.5 or even 1.21 might be out! We'll be sure to make sure the mod is available on the relevant versions at the time.

**Comment by sleepingdragoninn** [comment]
Replacing this with a roll-up issue
