### ISSUE TITLE
1.20.1 Quilt, Atlas crafting does not work

### ISSUE THREAD

**Issue by NovelPhacelia** [sleepingdragoninn/antique-atlas#53]
![image](https://github.com/sisby-folk/antique-atlas/assets/83443727/7217ec33-d866-4ad9-96da-d0de9d3730c6)
Running mod on Quilt 0.24.0 (latest as of writing) and Minecraft 1.20.1 with only this mod and qsl, the atlas does not show up after putting a book and compass in the crafting table (the original mod's recipe)

**Comment by sleepingdragoninn** [comment]
the atlas item does not exist in antique atlas 4 - only the hotkey is used.

**Comment by NovelPhacelia** [comment]
wow thanks for the fast response, but will the atlas as a item ever be added

**Comment by sleepingdragoninn** [comment]
version 2.0 is in alpha right now, and operates entirely on the client side - so its not immensely likely for that reason, but is still possible.
