### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by xAggresivER** [sleepingdragoninn/antique-atlas#56]
Okay so i found a bug in my modpack with your map i'm hosting sever for my friends and when i/them join just on the server our map looks like this 
![image](https://github.com/sisby-folk/antique-atlas/assets/163871208/3481367e-880f-4ee0-95ed-26cb80f248fa)

and when we join singleplayer world and than join server map looks normal
![image](https://github.com/sisby-folk/antique-atlas/assets/163871208/ab923d90-59d0-448e-a1c7-dac7e1e12d1e)

**Comment by sleepingdragoninn** [comment]
This *should* have been fixed in 1.4.3 - otherwise, send your logs/latest.log from https://mclo.gs/ after starting the game and joining the server once.
