### ISSUE TITLE
Vanilla Biome: Red Sand (Badlands Valley) 

### ISSUE THREAD

**Issue by sleepingdragoninn** [sleepingdragoninn/antique-atlas#61]
Badlands Valley currently uses the generic sand texture, but it could be tweaked slightly to give red sand a unique look. Badlands also have more frequent shrubs, which could be represented as well.

**Comment by lumiscosity** [comment]
added in [1a09fa8](https://github.com/sisby-folk/antique-atlas/commit/1a09fa80bfa1c86ede9019907e25294818b6188f), can be closed
