### ISSUE TITLE
Crash when placing two markers

### ISSUE THREAD

**Issue by lumiscosity** [sleepingdragoninn/antique-atlas#68]
Seems to be a 2.0 bug, I'm on the latest github build.
When one marker is placed, it won't appear until the world is reloaded. If two markers are placed, the game crashes, but the marker is saved.

**Comment by lumiscosity** [comment]
https://mclo.gs/6LmDzk5 confirmed for 2.0 beta 3, also happens when removing markers as seen here

**Comment by sleepingdragoninn** [comment]
point and laugh

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/91418e6a-50ed-4db4-975a-774eb88a3ef6)

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/15417ad6-a1f6-4a50-b240-fd23dc51a236)

fixed with surveyor beta 22
