### ISSUE TITLE
Seems to have issues with Immersive Portals

### ISSUE THREAD

**Issue by Lauriichan** [sleepingdragoninn/antique-atlas#69]
It seems like the atlas doesn't load the map or any markers on dimension change when used with Immersive Portals

**Comment by Lauriichan** [comment]
Is there a plan to fix this issue or will it stay?
I should also mention that rejoining in the dimension (other than the overworld) will cause the map to load successfully otherwise it will just be like I never was in that dimension.

**Comment by Lauriichan** [comment]
This is still the case in 2.2.0 (with surveyor)

**Comment by sleepingdragoninn** [comment]
inherently requies #75 - track it there and once that's done, feel free to try again.
