### ISSUE TITLE
"Unidentified Biome" Texture for modded biomes?

### ISSUE THREAD

**Issue by Dumpling00** [sleepingdragoninn/antique-atlas#78]
For your consideration:
Since I'm assuming adding custom textures for every modded biome out there is unfeasible, would it be possible to simply add a "generic/mysterious/unidentified Biome" texture to replace all unregognized biomes added by other mods?

Anything other than the ugly eye-punching bright colors that we get right now?

Thank you so much for your time.

**Comment by sleepingdragoninn** [comment]
You shouldn't be getting eye punching textures in 1.4.3 or 2.0, that would represent a serious bug!

We've considered swapping out the fail texture for tiny little `?????`-s, but since we made fallback textures (which are way better) cover almost every case we've been less interested - what's up with your instance?

**Comment by Dumpling00** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/44829013/d9e63127-01be-4605-af9b-82ca4c8f694f)

Thank you for your timely response! This is what I'm getting right now - I've correctly identified all biomes to be from Nature's Spirit. Not sure if that helps!

I'm on Fabric 1.20.1!
Thank you in advance!

**Comment by sleepingdragoninn** [comment]
That does! can you also upload your logs/latest.log file to https://mclo.gs/ and post the link?

**Comment by Dumpling00** [comment]
https://mclo.gs/DsKEvvp Here it is from the live session I've just opened to take the picture!

Worth mentioning my minecraft is HEAVILY modded though. But yeah, hopefully something can be done!
Thank you again so much.

**Comment by sleepingdragoninn** [comment]
![Screenshot_20240403-101014](https://github.com/sisby-folk/antique-atlas/assets/55819817/db0914c6-7c3b-498f-a33e-f1bb9cd8dbc4)

Very interesting! Looks like some of the nature's spirit biomes have biome tags, but some of them don't! You can ask nature's spirit to add their biomes to relevant tags like `c:is_forest`, but considering how many mods seem to fail this check in your instance, we'll add a slightly more subtle fail texture as originally planned.

**Comment by sleepingdragoninn** [comment]
You're also welcome to filter to just errors in your log, search for `no fallback could be found` and write down all the mods that fail the biome tag check - if you want to go on an adventure of asking them to add conventional tags - we check every conventional *and* forge biome tag, so they can pick any of those. 

If a mod is placing biomes in the overworld it should *usually* have a valid conventional biome tag (even if it's just c:is_temperate) - exceptions for unique dimensions like bumblezone where it might not make a lot of sense, or technical biomes that aren't actually used.

**Comment by sleepingdragoninn** [comment]
Here's the list of all of our fallback tag mappings as well: https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/java/folk/sisby/antique_atlas/reloader/BiomeTileProviders.java#L78 in case any biome mods need to know what tags are available to them that will work

**Comment by Dumpling00** [comment]
Thank you SO much. Yeah - I'm running a heavy exploration based campaign with some friends so we're putting in a lot of biome mods. If you have a way to fix this, even if the Atlas won't be 100% accurate, it would be absolutely fantastic!

I will try to report this issue to the other devs but I'm afraid it might take a lot - and I'm personally always very wary of updating biome and world-gen based mods on an already on-going world/campaign, so I'd take anything that can get rid of the eye-sore really!

**Comment by sleepingdragoninn** [comment]
Not at all a problem - we'll probably have some free time to do that today now that we've cooled down from the big update

**Comment by Dumpling00** [comment]
Here's an updated copy of the log with just errors!

https://mclo.gs/DsKEvvp

Honestly look at this now, it's a miracle my instance still boots up haha.

**Comment by sleepingdragoninn** [comment]
Released as 2.1.0 - have fun!

![042c2f2a17ff079dec1ffdb213f30dc17d63b393](https://github.com/sisby-folk/antique-atlas/assets/55819817/cfad5dbd-8369-4115-b83e-679e9d36b53d)
