### ISSUE TITLE
More crashes with Atlas :(

### ISSUE THREAD

**Issue by Dumpling00** [sleepingdragoninn/antique-atlas#79]
Hey there, thank you for yesterday's fix! Things seemed to work well, until this started happening: Not sure why, the log references Atlas. Keeps getting the same error in log until it eventually crashes the game.

Help please? Here's the report.

https://mclo.gs/ba75Tjh

Apologies, tried to copy the Errors only version but it keeps giving me the whole log.

Thank you again so much for your time.
     
              Released as 2.1.0 - have fun!

![042c2f2a17ff079dec1ffdb213f30dc17d63b393](https://github.com/sisby-folk/antique-atlas/assets/55819817/cfad5dbd-8369-4115-b83e-679e9d36b53d)

_Originally posted by @sisby-folk in https://github.com/sisby-folk/antique-atlas/issues/78#issuecomment-2033290766_

**Comment by sleepingdragoninn** [comment]
I don't see any crash in this log - are you sure you copied in the right one? The errors that read `No fallback could be found` are expected - these are what lead to the question mark texture.

**Comment by Dumpling00** [comment]
Seems like the issue solved itself - I believe it was "better chunk loading" or something completely different that somehow resolved itself. Sorry to waste your time!
