### ISSUE TITLE
A Ton of -> Error reading structure tile provider [Fabric 1.20.1]

### ISSUE THREAD

**Issue by xR4YM0ND** [sleepingdragoninn/antique-atlas#82]
Just one of million log entries:
```
[Antique Atlas] Error reading structure tile provider minecraft:piece/jigsaw/single/village/taiga/zombie/streets/straight_06!
java.lang.IllegalStateException: texture antique_atlas:structure/village/path_horizontal is not present!
```

[latest.log](https://gist.github.com/xR4YM0ND/3962bab0634345afb6a2e1acfa553554)

**Comment by sleepingdragoninn** [comment]
It looks to me like the texture reloaders are either firing at the wrong time or not at all - can you use this jar and send a fresh latest.log to https://mclo.gs/ ?
[antique-atlas-2.2.0+1.20.jar.zip](https://github.com/sisby-folk/antique-atlas/files/14878598/antique-atlas-2.2.0%2B1.20.jar.zip)

I've just added loggers when each reloader starts so we can confirm they're running in the right order.

**Comment by xR4YM0ND** [comment]
I can't reproduce this issue now...
Worked on the modpack and now ain't happening.

I'm going to test this if this issue happens again

**Comment by sleepingdragoninn** [comment]
I'll close this for now but let us know with a log if it crops up again!

**Comment by pajicadvance** [comment]
I was updating my modpack and this exact same log spam started popping up. Tried on a clean instance, there is no log spam. I assume this is a mod conflict. I'm in the process of figuring out which mod is causing the conflict. Using Antique Atlas 4 2.7.0 on 1.20.1.

**Comment by pajicadvance** [comment]
Disabling [Yet Another Config Lib](https://modrinth.com/mod/yacl) gets rid of the log spam.

**Comment by xR4YM0ND** [comment]
Ok i have a new log with this issue
-> with your Antique Atlas 2.2.0 you sent here in github: https://mclo.gs/Jjo8wrA
-> with modrinth Antique Atlas 2.7.0: https://mclo.gs/V845LWC

**Comment by xR4YM0ND** [comment]
You're right @pajicadvance 

The mod `Sounds` embedds Yet another config lib -> without Sounds mod no log spam

**Comment by sleepingdragoninn** [comment]
The log confirms that the reloaders are running in the wrong order - that's not on us for sure - we specify [here](https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/java/folk/sisby/antique_atlas/reloader/StructureTileProviders.java#L238) that textures need to run first - something is breaking the order.

**Comment by sleepingdragoninn** [comment]
can this be reproduced in an instance with only AA, YACL, and FAPI?

**Comment by xR4YM0ND** [comment]
Here is the log without `Sounds & Yet another config lib`
Also running Antique Atlas 2.2.0 from this github thread:
https://mclo.gs/LCwRIF2

Is the order correct in this log?

**Comment by pajicadvance** [comment]
YACL has a reload listener for images: https://github.com/isXander/YetAnotherConfigLib/blob/multiversion/dev/src/main/java/dev/isxander/yacl3/gui/image/YACLImageReloadListener.java, and it's not overriding `getFabricDependencies()`.

> can this be reproduced in an instance with only AA, YACL, and FAPI?

Yes

**Comment by sleepingdragoninn** [comment]
we kept the loggers permanently, so you can use the latest version of AA.

Considering that YACL touches reloaders at all, I'm guessing it breaks it accidentally?

**Comment by sleepingdragoninn** [comment]
![Screenshot_20240428-231147](https://github.com/sisby-folk/antique-atlas/assets/55819817/e2e42eeb-5c96-4c1a-9327-1a5183224ba4)

and yes that log does show the correct order - tiles before biomes, tiles *and* markers before structures.

**Comment by pajicadvance** [comment]
Opened an issue report about this on the YACL repo

**Comment by isXander** [comment]
YACL does nothing unusual with reloaders, it's quite a basic implementation - if you have any insights lmk.

**Comment by sleepingdragoninn** [comment]
the thing that specifically appears to be failing is fabric's IdentifiableResourceReloadListener#getFabricDependencies - our dependent reloader is running before the dependency.

Seeing as this can be reproduced in isolation, maybe there's some way you could slice up the mod a bit to confirm which part causes it?

**Comment by isXander** [comment]
One thing I think I may be doing wrong is calling the preparationbarrier multiple times in the reload. That can't be good.
