### ISSUE TITLE
Crash on joining world (Single Player, Fabric 1.20.1)

### ISSUE THREAD

**Issue by Dumpling00** [sleepingdragoninn/antique-atlas#84]
Hi there! Sorry again, things were working fine before, but after updating, I'm crashing on  joining my single player world, and the logs seem to stop at Atlas?

There's a bunch of errors happening at  03:17 - I was wondering if this was indeed an Atlas thing or something else?
I have also updated the framework.

https://mclo.gs/LtMqYLZ

**Comment by sleepingdragoninn** [comment]
Again no actual crash in this log, these are just regular errors, not a crash with a stack trace + modlist

**Comment by sleepingdragoninn** [comment]
Is your game freezing/hanging, not crashing? If so, it could be any mod - you don't get proper crash logs or stack traces for that kind of issue, and the AA logs are normal operation (see the pinned issue)

**Comment by Dumpling00** [comment]
> Is your game freezing/hanging, not crashing? If so, it could be any mod - you don't get proper crash logs or stack traces for that kind of issue, and the AA logs are normal operation (see the pinned issue)

Yeah I don't know what to say, honestly, I'm sorry - it hangs on the loading screen for a few seconds after joining world, then it force quits itself with modrinth saying this, and the log page shows what I've shared.
![image](https://github.com/sisby-folk/antique-atlas/assets/44829013/2cb1526c-dbca-47fa-8c4b-21f20e18a81e)

However, I've tried again disabling Atlas and Framework, so they can't be the one causing the issue.
I'm stumpted, it could be Bumblezone or Slayer's Beasts since I've also updated those two, but if the log shows nothing I have no pointers :(

**Comment by Dumpling00** [comment]
Ok, I've rolled back Bumblezone and  Slayer's Beasts to the previous version and everything works again. Sorry once again.
Next time I'll make sure to test again without the mod to make sure the crash only happens when the mod is active. But if it doesn't show the actual crash, I don't know what to do.

Again sorry to waste your time.

**Comment by sleepingdragoninn** [comment]
no problem - have fun with atlas!

**Comment by Dumpling00** [comment]
> no problem - have fun with atlas!

Oh. and.. well, um. I've heard of this, I guess Immersive Portals and Atlas aren't quite a match just yet.

![image](https://github.com/sisby-folk/antique-atlas/assets/44829013/1e4671ff-b005-4ae5-b17d-ed97fa9de825)

Seems like there's always something, haha.
Can this be fixed in any way, by chance?
