### ISSUE TITLE
Minecraft detects only one modification version

### ISSUE THREAD

**Issue by LeoWyze** [sleepingdragoninn/antique-atlas#89]
I encountered a problem, Minecraft does not detect any version of the modification other than 0.9.0-1+forge-1.20. Architectury API and Cloth Config API are set to the latest for version 1.20.1.

**Comment by sleepingdragoninn** [comment]
sounds like you're trying to run version 2.x without Sinytra Connector and FFAPI! unfortunately, due to limitations in how modrinth handles version dependencies, we can't flag for these explicitly.
