### ISSUE TITLE
Crash with portal blocks to a mod's custom dimension (Spectrum)

### ISSUE THREAD

**Issue by murphy-slaw** [sleepingdragoninn/antique-atlas#91]
When Antique Atlas and Spectrum are both installed, if any entity or player collides with a `spectrum:deeper_down_portal ` block, the game crashes. This is a portal block which leads to Spectrum's custom "Deeper Down" dimension. 

Disabling Antique Atlas prevents the crash. Crash report attached.

Minecraft 1.20.1
Antique Atlas 4 2.4.0+1.20
Spectrum 1.7.8

[crash-2024-04-11_08.11.32-server.txt](https://github.com/sisby-folk/antique-atlas/files/14949238/crash-2024-04-11_08.11.32-server.txt)

**Comment by sleepingdragoninn** [comment]
Does the crash occur if you manually do `/execute in [dimension] run tp 0 100 0`? or only when touching the portal block

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/c64df090-eab9-41fa-bc8b-4054753b80a7)

if i was to guess, this might be related to deeper down being exclusively negative Y values

**Comment by sleepingdragoninn** [comment]
I believe this is the problem:

![image](https://github.com/sisby-folk/antique-atlas/assets/55819817/77dc7037-d379-466e-9eb3-ab2005720685)

When the minimum y coordinate of a dimension is  below zero, we add a layer at zero - this is true of deeper down, but it does not actually have blocks at zero, causing the issue. I'll spin up a fix.

**Comment by murphy-slaw** [comment]
The teleport command causes the same crash.

`/execute in spectrum:deeper_down run tp 0 100 0`

gives this crash report

[crash-2024-04-11_18.21.00-server.txt](https://github.com/sisby-folk/antique-atlas/files/14952941/crash-2024-04-11_18.21.00-server.txt)

**Comment by sleepingdragoninn** [comment]
[surveyor-0.1.4+1.20.jar.zip](https://github.com/sisby-folk/antique-atlas/files/14952959/surveyor-0.1.4%2B1.20.jar.zip)

Here's the fixed version of surveyor, which should override the version inside antique atlas - can you confirm this fixes the issue?

**Comment by murphy-slaw** [comment]
With the updated surveyor installed, no crash. Thanks!

**Comment by sleepingdragoninn** [comment]
No problem! We'll put this fix in the next release.

**Comment by sleepingdragoninn** [comment]
updated in AA now!
