### ISSUE TITLE
Causes uncorrectable lag(forge 1.20.1)

### ISSUE THREAD

**Issue by efficient-efi** [sleepingdragoninn/antique-atlas#94]
![2024-04-09_14 41 04](https://github.com/sisby-folk/antique-atlas/assets/117365833/9bc15358-84d0-4a2a-ba5a-31d6151d6a06)
Used in conjunction with just a few world gen mods, it causes major lag spikes and makes the game unplayable.

[mod list - all of them are latest version]
antique atlas
embeddium
ferritecore
immediatelyfast
modernfix
radium
oculus
wyther's expanded ecosphere

**Comment by efficient-efi** [comment]
This screenshot was taken with a different mod configuration, but the problem happening was the same, and removing the antique atlas mod solved it.

**Comment by sleepingdragoninn** [comment]
you'll need to take spark profiles for this one - `/sparkc profiler start --timeout 60` and `/spark profiler start --timeout 60`

**Comment by efficient-efi** [comment]
[without atlas]https://spark.lucko.me/ZGM6x6ON8L
[with atlas]https://spark.lucko.me/pWuP21Uyld
It is not detected by spark, but still causes a significant lag spike when the atlas mod is installed.

**Comment by sleepingdragoninn** [comment]
you're running atlas 1.x on 1.20 - we completely rewrote the backend in 2.0, and carefully profiled it for performance.

It'll clear your map exploration when you update, but you shouldn't experience the same lag.

**Comment by efficient-efi** [comment]
I reset the config file and it fixed it! I must have set the scan distance too far, my bad.
I'll try the 2.0 version.

**Comment by sleepingdragoninn** [comment]
no problem! in 2.0 the scan distance is always 100% of all loaded chunks, no more, no less - so there's no option to accidentally mess up anymore ^^
