### ISSUE TITLE
Structure Related Crash on Worldload (Forge 1.20.1)

### ISSUE THREAD

**Issue by Liamgrayskull** [sleepingdragoninn/antique-atlas#95]
This is with a full in-development release of https://modrinth.com/modpack/inquisitive, based upon sinytra connector, introducing antique-atlas 2.5.0 causes the crash)

[crash-2024-04-20_21.24.01-server.txt](https://github.com/sisby-folk/antique-atlas/files/15050652/crash-2024-04-20_21.24.01-server.txt)

The error seemingly persists from antique atlas 2.0.0 onwards, a crash from 2.0.0 is here for reference:
[crash-2024-04-20_21.35.07-server.txt](https://github.com/sisby-folk/antique-atlas/files/15050672/crash-2024-04-20_21.35.07-server.txt)

Let me know if this error is diagnosable now, or if a binary test is due/any suspect mods are worth checking out initially. disabling structure markers in the antique-atlas.toml file doesn't seem to have any effect on the error. (Thank you for this uniquely wonderful mod)

**Comment by sleepingdragoninn** [comment]
I think this indicates that you  have a structure in your pack that exists, but doesn't have a registered ID, or possibly no registered type - I'll have a look, and make a non-crashing route for that.

**Comment by sleepingdragoninn** [comment]
Yep this line 

`RegistryKey<Structure> key = world.getRegistryManager().get(RegistryKeys.STRUCTURE).getKey(start.getStructure()).orElseThrow();`

you have a structure in the world, but that isn't registered to the structure registry,

**Comment by sleepingdragoninn** [comment]
@Liamgrayskull here's your crash fix - https://modrinth.com/mod/surveyor/version/0.3.2+1.20 see if dropping that into the modpack resolves the issue - it should ideally also give you a good guess at what the problematic mod is in the log, so feel free to post your `logs/latest.log` from https://mclo.gs/ so it can be reported on their end.

**Comment by Liamgrayskull** [comment]
Thank you so much for the help! Dropping that in has fixed the issue on my end, everything seems perfectly functional, and the latest log is here:

This excerpt is the sole structure error I was able to find- far as I know there's nothing currently installed that affects ruined portals (except for *maybe* frame changer, but iirc that only adds obsidian block variants, not change portal gen), but I'll keep an eye out.

[25Apr2024 16:42:26.727] [Server thread/ERROR] [net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer/]: Exception loading structure piece with id minecraft:rupo
java.lang.IllegalArgumentException: No enum constant net.minecraft.world.level.block.Mirror.
	at java.lang.Enum.valueOf(Unknown Source) ~[?:?]
	at net.minecraft.world.level.block.Mirror.valueOf(Mirror.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.world.level.levelgen.structure.structures.RuinedPortalPiece.m_229165_(RuinedPortalPiece.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]
	at net.minecraft.world.level.levelgen.structure.structures.RuinedPortalPiece.m_229185_(RuinedPortalPiece.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23792!/:?]

https://mclo.gs/iNKxwJB

(debug.log in the off chance that helps in any sort of way)
https://mclo.gs/BNDgyeL

**Comment by sleepingdragoninn** [comment]
The relevant line is `[25Apr2024 16:42:04.588] [Server thread/ERROR] [surveyor/]: Encountered an unregistered structure! net.minecraft.world.level.levelgen.structure.StructureStart@2284c097 \| null`

This tells us that it's a structureStart with quite literally no structure at all - so a mod is doing something very funky. You could technically bisect to isolate which mod is misbehaving, but it's probably not worth it :joy:

Glad to hear it fixed the issue! We'll make sure that version is in the next AA release.
