### ISSUE TITLE
client crash when joining a multiplayer server

### ISSUE THREAD

**Issue by 800020h** [sleepingdragoninn/antique-atlas#96]
[crash-2024-04-24_17.57.11-client.txt](https://github.com/sisby-folk/antique-atlas/files/15090744/crash-2024-04-24_17.57.11-client.txt)

it doesn't seem to happen every time

minecraft 1.20.1
AA 2.6.0+1.20
https://modrinth.com/modpack/spectrum-public-server-pack/version/2.1.0

**Comment by 800020h** [comment]
the server and client had just updated from AA 2.5.0+1.20

**Comment by sleepingdragoninn** [comment]
Can you check if adding https://modrinth.com/mod/surveyor/version/0.3.1+1.20 fixes it? if so we'll pack it in the next release.

**Comment by 800020h** [comment]
when I updated I had to create a new instance
and I didn't copy the surveyor data from the old one at first
but after copying it I was able to connect
I'm not sure if that is why I was able to connect, or if it was just random

**Comment by sleepingdragoninn** [comment]
I'll assume the bugfix works then - it'll be in 2.7!

**Comment by 800020h** [comment]
> Can you check if adding https://modrinth.com/mod/surveyor/version/0.3.1+1.20 fixes it? if so we'll pack it in the next release.

confirmed working by another player on the server
